### ISSUE TITLE
Drives approved but not moving to LIVE status

### ISSUE THREAD

**Issue by nokton** [Safecast/safecastapi#119]
12632	2013/04/20 01:01	 masato tsubaki	162-0419.LOG
福島県会津若松市内～喜多方 -  masato tsubakiが運転	 3,026	 Submitted

12629	2013/04/19 11:03	 GLC	156-0418.LOG
山口 -  GLC	 8,307	 Submitted

12628	2013/04/19 11:00	 GLC	156-0417.LOG
佐賀 -  GLC	 8,681	 Submitted

12605	2013/04/16 07:39	 masato tsubaki	162-0410.LOG
足立区～福島県 福島市内 東北道経由 -  masato tsubakiが運転	 4,035	 Submitted

12579	2013/04/13 12:48	 GLC	159-0410.LOG
岩手 -  GLC	 10,201	 Submitted

**Comment by seanbonner** [comment]
Same as #118
