### ISSUE TITLE
Drives stuck in approval - data points not generated

### ISSUE THREAD

**Issue by nokton** [Safecast/safecastapi#120]
12425	2013/03/15 02:48	 GLC	154-0309.LOG
宮城県 -  GLC	 0	 Submitted (Not Approved)
12424	2013/03/15 02:47	 GLC	154-0308.LOG
宮城県 -  GLC	 0	 Submitted (Not Approved)
12423	2013/03/15 02:46	 GLC	154-0305.LOG
宮城県 -  GLC	 0	 Submitted (Not Approved)
12422	2013/03/15 02:44	 GLC	154-0304.LOG
宮城県 -  GLC	 0	 Submitted (Not Approved)
12320	2013/03/04 01:54	 GLC	157-0226.LOG
宮城県 -  GLC	 0	 Submitted (Not Approved)
12303	2013/02/26 04:54	 GLC	157-0225.LOG
宮城県 -  GLC	 0	 Submitted (Not Approved)
12157	2013/02/15 01:38	 GLC	150-0209.LOG
鹿児島県 -  GLC	 0	 Submitted (Not Approved)
12156	2013/02/15 01:36	 GLC	150-0208.LOG
大分県 -  GLC	 0	 Submitted (Not Approved)
12124	2013/02/14 12:24	 GLC	150-0129.LOG
鹿児島県 -  GLC	 0	 Submitted (Not Approved)
12089	2013/02/07 12:26	 GLC	150-0128.LOG
鹿児島県 -  GLC	 0	 Submitted (Not Approved)
12088	2013/02/07 12:23	 GLC	150-0127.LOG
宮崎県 -  GLC	 0	 Submitted (Not Approved)

**Comment by seanbonner** [comment]
This list is 10000000x longer now and part of another issue so closing this.
