### ISSUE TITLE
A general introduction to the apps here?

### ISSUE THREAD

**Issue by Xenofex** [Safecast/safecastapi#125]
Hello @seanbonner!

Can you help me run the whole system in the local development environment? This sounds weird but I'm new to here. Before doing any actual work, can I get a overview picture of the whole system, not only this app but also the apps that is relying on this? I downloaded the code, made it run in my computer, created a user and a moderator, found some sample logs from the tickets here, successfully imported it, but what else can I do with the site?

[GeoSence](https://github.com/Safecast/GeoSense) is one of those calling this app, right? I also downloaded it, ran it. But I don't know what I can do with it, like that how can I connect this to my local safecastapi? 

When I tried to create a map from the index page, I got an error:

    TypeError: Invalid hex string:
        ...
        at /Users/eli/Projects/GeoSense/api/map/index.js:134:16
        ...

where `new Buffer(uuid.v4(), 'hex')` is called. I tired in the eclipse debugger, finding that `uuid.v4()` returns a string like "788f0bdc-a2a2-4b57-ac69-78a4a6d6ca31", which is not a hex. Is it a bug? 

Thanks!

**Comment by matschaffer** [comment]
@robouden would you maybe have enough experience with the system to answer this? Even some rough notes would probably be helpful.

**Comment by robouden** [comment]
Xenofex.. 

Sorry for the late reply..Paul is often very busy. Thereby some information about the Safecast API

* Basically the system consists of a DB(Postgres and Postgris) and the Ruby API. 
* Data is imported through the webfront as bGeigie imports and and Measurements.
* Maps are created automatically.From the imported log files.
* The data can be access through the queries to the web server.
* The setup can used as a production, dev and a test environment.
* Geosense project is stalled.
* Most of the features work, but some are never finished or not implemented.

**Comment by matschaffer** [comment]
Here's a simple diagram attempt. What actually creates the maps from the imported log files. Is it the Rails app?

I know there are there are the dynamic maps in-page for each upload but what about stuff like http://safecast.org/tilemap/ ?

```
                  +-------+                
                  |Postgis|                
                  +---^---+                
                      |                    
                      |                    
                      |                    
                      |                    
                 +----+----+               
    bGeigies+---->Rails API+---------> maps
+---+            +----^----+               
| +---+               |                    
| |  +--+             +                    
+-|  |  |      API applications            
  +- |  |                                  
     +--+                                                                
```

**Comment by Frangible** [comment]
It depends what you mean by "maps".  The Tilemap page has pretty comprehensive high-level documentation and I believe the data flow diagram should address your questions; I created it specifically for cases like this.  If it does not, let me know and I will fix it.

<img width="728" height="546" src="https://github.com/Safecast/Tilemap/raw/master/docs/webmap_dataflow_full_2048x1536.png" />

See the Tilemap readme for context.  It doesn't cover input, but that is to my knowledge the most comprehensive diagram of what you're looking for.  Also, note that the native apps download ios13_32.sqlite directly.

As you mention there are also embedded maps on the API site, but I am not very familiar with them.  Ideally, it would be desirable to replace whatever embedded map functionality is present in the Ruby app with bgeigie_viewer.js from Tilemap.

Let me know of any more questions but I think the Tilemap documentation should be able to help give you at least an overview of things.

**Comment by nokton** [comment]
Hi Matt,

Do you mean Tile maps, or the map shortly shown after importing the drive file?

Pieter

**Comment by matschaffer** [comment]
Both actually. By "the dynamic maps in-page for each upload" I meant the map shortly shown after uploading/importing the drive file. And I presume http://safecast.org/tilemap/ is generated from the Tile maps.

Either way I've fleshed out the readme a bit in #177. Hopefully that helps others who come into the project looking for context.

**Comment by robouden** [comment]
Xenofex:

From the 2014 API Hackathon we have some documents. If you want to see then let me know.

regards
rob

**Comment by Frangible** [comment]
Xenofex is no longer a contributor.

**Comment by nokton** [comment]
Those maps are separate objects, though I would say having the Tilemap doing the rendering after upload would be nice.

**Comment by matschaffer** [comment]
That would definitely be nice. Will have to get my hands deeper into the
whole pipeline before taking a crack at such a feature.

2015年6月9日火曜日、Pieter Franken<notifications@github.com>さんは書きました:

> Those maps are separate objects, though I would say having the Tilemap
> doing the rendering after upload would be nice.
>
>
> > On Jun 5, 2015, at 11:09 PM, Mat Schaffer <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Both actually. By "the dynamic maps in-page for each upload" I meant the
> map shortly shown after uploading/importing the drive file. And I presume
> http://safecast.org/tilemap/ <http://safecast.org/tilemap/> is generated
> from the Tile maps.
> >
> > Either way I've fleshed out the readme a bit in #177 <
> https://github.com/Safecast/safecastapi/pull/177>. Hopefully that helps
> others who come into the project looking for context.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/Safecast/safecastapi/issues/125#issuecomment-109304621
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Safecast/safecastapi/issues/125#issuecomment-110261892>
> .
>


-- 

-Mat

about.me/matschaffer
