### ISSUE TITLE
Documentation for bulk import needed

### ISSUE THREAD

**Issue by seanbonner** [Safecast/safecastapi#127]
If someone contacts us and wants to generate logs from their own device and then upload those (or interface with our API to stream the data to us) there's no clear how to for them to do that. We need a simple straight forward documentation including a sample log that people can follow to start sending us data.

Use case: We have been contacted by several app and device manufacturers who want to allow their users to send their data to Safecast but can't figure out how to do it.

**Comment by thinrope** [comment]
It will be sometime till we fix that (and nobody has actively tried to send data to our API), but the format of the drive log is fairly simple to understand and documented, for example here: https://github.com/Safecast/bGeigieMini/blob/master/README.md#data-log-file-format

**Comment by seanbonner** [comment]
Chicken / Egg - No one has tried to send data because it's not documented how to do it. Several people have asked about how to do it and been unable to figure it out so they haven't done it.

**Comment by thinrope** [comment]
What kind of action do you envison? A specific HOWTO? Posted where?

# :sparkles:HOWTO:sparkles: submit log data
## (via Safecast API frontend: https://api.safecast.org/ )
1. Create data in the format of the Nano, see code for reference
-- https://github.com/Safecast/bGeigieMini/blob/master/examples/bGeigieMini/bGeigieMini.pde
-- https://github.com/Safecast/bGeigieMini/blob/master/README.md#data-log-file-format
2. Create account on the API frontend
-- https://api.safecast.org/users/sign_up
3. Upload the data via the API
-- https://api.safecast.org/bgeigie_imports/new
4. Add necessary metadata and submit for approval
5. Have a coffee or two each morning, wait for approval
6. After approval, on the next update (every few hours) it will be used for the map
-- http://safecast.org/tilemap

**Comment by seanbonner** [comment]
That's cute but entirely unhelpful. As stated in the initial post, we have been contacted by app and device manufactures who want to make it easy for their users to automatically send us data. Really, if you aren't interested in helping the situation I'm not sure why you are wasting your time mocking the problem.

**Comment by thinrope** [comment]
I am interested in helping, that is why I am spending time on this.

Initial post says:
> If someone contacts us and wants to generate logs from their own device and then upload those (or interface with our API to stream the data to us) there's no clear how to for them to do that. We need a simple straight forward documentation including a sample log that people can follow to start sending us data.
>
I provided a simple inline HOWTO explaining how someone can "generate logs from their own device and then upload those". Assuming that "someone" has basic dev skills and reads English, it is more than enough  as a start.
What is not OK in my comment? Too much sarcasm? When you decide where is this HOWTO going, it can be freely edited/expanded/translated to suit the audience.
(added one more URL)

**Comment by seanbonner** [comment]
No, linkslapping people and questioning their dev/language skills isn't enough to start, and yes it's way too much sarcasm. In the initial post I explained a problem and gave a specific use case that needs a solution:

"Use case: We have been contacted by several app and device manufacturers who want to allow their users to send their data to Safecast but can't figure out how to do it."

APPS. DEVICES. MANUFACTURES.

These are key details. Telling someone to go set up an account on api.safecast.org and upload their data isn't helpful at all. It's dismissive and insulting. It doesn't solve the proposed problem in anyway and worse it makes us sound like assholes. If you want to help write up a line by line, step by step instruction for a company to set up server connection to our API to send streams of bulk data to us. Don't be snarky. Don't act like it's obvious and they should already know it. Leave your ego at the door and try to put yourself in the position of a company who is interested in helping safecast. That's what is clearly being asked for here. If someone comes to us interested in helping and is greeted with a shitty attitude their interest in helping disappears in a second. If on the other hand we're helpful and provide useful info for them then something beneficial might come from it.

So if you want to help - do that.

Otherwise, at least don't make the situation worse.

**Comment by thinrope** [comment]
OK, I think I am better seeing this now, hopefully.
I was thinking about hackers/makers trying to upload data, not manufactures, thanks for clearing this up.

If we are talking about  manufacturers, especially of mass-produced devices, the usual way (in other open-source projects as well) is to find a developer (internal or external to the project) and let him/her work with the project and device building an interface. Usually that involves giving a device to the developer as well as actually supporting his/her work (answering questions, etc).

If we are talking about simple MCU-based radiation units, then reusing the code for any of our devices, should be trivial. If we are talking more high-end CPU devices, then sending HTTP POST requests is all it takes (say using curl library). With high-level libraries, it takes few lines of code, that simple (yes you need to set up account and get a key as described above).

What about getting proactive and have a mail or even a call with the said manufacturer and clear things up in the particular case?

**Comment by seanbonner** [comment]
Thank you, but again that's not what is being asked for here.

Right now we can solve any individual situation on a case by case basis. We don't have the consistent time or availability to do that, and shouldn't need to, which is why we want a resource that anyone can reference to solve this for themselves. This is not a specific, this is a general. We need a resource that applies across the board.

So again, if you'd like to be helpful and create that resource that would be wonderful, if you want to suggest that this problem doesn't need to be solved this way that isn't helpful at all.

**Comment by matschaffer** [comment]
Just scanning through tickets and came across this one. This doesn't sound like an API documentation issue as much as it does an API capability discussion. What Kalin describe is (afaik) the only way to get data in.

If manufacturers want to get their data into the system we'll need augmentation along the lines of what Pieter suggested such that the data can either be identified in our system along with all the other sensors or if that's not possible, isolated to a separate somewhat-less-moderated space.

**Comment by matschaffer** [comment]
I've opened https://github.com/Safecast/safecastapi/pull/510 as a "fix" to this since it at least demonstrates how bgeigie drives can be uploaded automatically.

I think if we have a specific case of a manufacturer looking to send data to us going forward we should:
- try to get that data going via ingest rather than api
- address any specific shortcomings for that device's ingest path once we know for sure what they are

**Comment by matschaffer** [comment]
To address generic documentation I also created https://github.com/Safecast/safecastapi/wiki/Publishing-new-data-points
