### ISSUE TITLE
Ability to send free message to contributor for admins

### ISSUE THREAD

**Issue by nokton** [Safecast/safecastapi#130]
On a drive, have a button for an admin to send a small message to a contributor. E.g. instructions for entering data on a drive, or anything else really. This could also be a simple http to call mail program with in the TO: the email of the contributor (so we can take it off line in email rather than do this in the app it self)

**Comment by matschaffer** [comment]
Probably done. Waiting on @jsidd for a final test now that everything is in prod.

**Comment by matschaffer** [comment]
Still holding on a final test. If the email's not getting through we may need to bump up priority on #332
