### ISSUE TITLE
filter by date on bGeigie imports does not work

### ISSUE THREAD

**Issue by thinrope** [Safecast/safecastapi#142]
example:
https://api.safecast.org/en-US/bgeigie_imports?utf8=%E2%9C%93&q=&approved=&by_user_id=6&uploaded_after=01%2F08%2F2013+00%3A53%3A26&uploaded_before=&by_status=&commit=Filter

I guess date format is wrongly specified by the GUI? Also on some dates (date >12), seems to crash, so month/date switched? IMHO using ISO8601 _everywhere_ saves a lot of pain...

**Comment by seanbonner** [comment]
Seems to be working now.
