### ISSUE TITLE
wrong rendering on "null" values

### ISSUE THREAD

**Issue by thinrope** [Safecast/safecastapi#143]
Example: https://api.safecast.org/en-US/measurements/26027811
JSON is fine:
{
    "captured_at": null,
    "device_id": 35,
    "id": 26027811,
    "location_name": null,
    "original_id": 26027811,
    "unit": "cpm",
    "user_id": 6,
    "value": 18,
    "latitude": 35,
    "longitude": 135
}

However the HTML rendering is offset/borked:

![scr](https://f.cloud.github.com/assets/754020/1280844/74d16a46-2f59-11e3-974e-4450ac01d604.png)

**Comment by matschaffer** [comment]
Fixed by #169
