### ISSUE TITLE
fixed sensors data in/out

### ISSUE THREAD

**Issue by thinrope** [Safecast/safecastapi#148]
We are beginning to add more data from new (!=Softbank/Keio) fixed sensors, starting with https://api.safecast.org/en-US/devices/40/measurements
(here is an open issue #6, but that is focused on importing current Softbank/Keio sensors, so not very related)

It will be a good to have dedicated interface for such data since we only need time/value.

**Comment by matschaffer** [comment]
Closing this down since fixed sensor input is now handled via ttserve/ingest/(graf|kib)ana.
