### ISSUE TITLE
Need to authenticate data downloaded via the API

### ISSUE THREAD

**Issue by seanbonner** [Safecast/safecastapi#158]
Seems like this is important to consider.

**Comment by thinrope** [comment]
What is the goal of the verification?
All drives are uploaded after login/authentication, so if A can login/submit drive, A can get access to the key as well; and A can submit any data in the right format.

Is there any other scenario to cover?

**Comment by seanbonner** [comment]
This was added during a conversation and was under the thought of a DB breach, not a user account. Or someone claiming they DL'd a log from Safecast and saying data is ours when it isn't.

**Comment by thinrope** [comment]
If we had DB breach (i.e. SQL injection) such that people INSERT/DELETE data, there is no direct way to protect against (except having backup such as S3). I'll address such possibility in solving issue #202 en passant.

If somebody claims they DL something from our site and it is not there, they have to prove (provide logs, timestamps, packet captures, etc) and we'll verify our logs (hopefully we have them). But we cannot prevent data forgery attempts with simple hashing. If we need to do that, the standard way is to sign the data that is going out of the API with a key inside the server (not user-accessible). While that may be a good idea, it will be an overkill at the current situation and will further strain the resources (both computational and developer). If you think that is needed, I'll split this issue into a new one "Authenticate data downloaded from the API" and refile it, but I doubt someone is available/eager to work on that now.

**Comment by seanbonner** [comment]
Let's not pretend we know how eager or available everyone is - this was added from a discussion where some people seemed concerned, if there's a better way to address it that's great and that should be noted in discussion.

**Comment by matschaffer** [comment]
I think this is pretty well covered by https://github.com/Safecast/safecastapi/issues/379 which describes a method where each point would get signed by any number of contributors. Any downloaded data could then be cryptographically checked against the public key of the signer.

As such closing this on down and hopefully someone can pick up work on the multi-signing idea.
