### ISSUE TITLE
Manually submitted measurements assigned wrong unit

### ISSUE THREAD

**Issue by Frangible** [Safecast/safecastapi#166]
Abstract:
Submitting a measurement via https://api.safecast.org/en-US/measurements/new and selecting "uSv/h" leads to a measurments row being inserted with unit "microsievert" and "usv" which prevents display on the API site using a unit filter.

Steps to reproduce:
1.  Go to https://api.safecast.org/en-US/measurements/new, submit a new uSv/h measurement (note: this is a PRODUCTION DATABASE, please do not submit a bad test measurement)
2.  Find your newly submitted measurement via entering the lat/lon on https://api.safecast.org/en-US/measurements.
3.  Now click "uSv/h" instead of "All".  The measurement is not displayed.

Expected behavior:
- The measurement submitted above is displayed

Actual results:
- It is not displayed.

Notes:
This is because the unit is not "usv", but rather "microsievert".  (both are technically wrong as they are not rates, merely dose equivalents, but that's another issue beyond the scope of this issue)

Fix:
In https://github.com/Safecast/safecastapi/blob/master/app/views/measurements/new.html.erb, modify line 51:
From: ['μSv/h', 'microsievert'],
To: ['μSv/h', 'usv'],

I do not see any additional dependencies in the measurement model but someone with more Ruby knowledge should verify this.

Actionable:
Yes.

Expected Time:
< 1 hour

**Comment by Steven-Wright** [comment]
This indeed should take about 15 seconds to fix. It also should have been caught by a test.
