### ISSUE TITLE
enh(improvements): general modernisation

### ISSUE THREAD

**Issue by evadne** [Safecast/safecastapi#170]
## Code
- ~~In `config/routes.rb`, redirect non-API routes to API routes (opposite from current approach)~~ (@matschaffer: removing this since it looks like most of our requests the non-API routes)
- [ ] In `config/routes.rb`, move `root :to` to last
## Infrastructure
- [x] Bump Rails 3.2 to latest release in preparation for 4.x
- [x] Convert `db/schema.rb` to `db/structure.sql`
- [x] Make `db/seeds.rb` meaningful
- [x] Revisit Postgres setup and pool size in `app/database.yml`
- [x] Revisit RSpec suite coverage and accuracy
- [x] Bump to rails 4 (or even 5 prerelease)
- [x] Bump Ruby to MRI 2.x
- [ ] Control all environment variables in `app/database.yml` using Dotenv
- [ ] Control all remaining environment variables using Dotenv
- [ ] Fix Procfile, change `custom_web` to `web`, do not daemonise Unicorn
## Operations (cloud66-specific items struck given likely AWS Migration)
- ~~Retrieve Monit script from Production and place under source control~~
- ~~Convert existing deployment process to Capistrano if possible and necessary~~
- ~~Find a safer way to keep Safecast SSL certs safe and tracked (move out of repository)~~
- [x] Revisit whether `ey.yml` is necessary
- [ ] Remove Typekit integration (doesn't currently work anyway)
## Optimisation / Refactoring
- [x] Distinguish Import File vs Measurement vs Import Job
- [ ] Remove `config/schedule.rb` (c66 & aws both have their own cron mechanisms)
- [x] Fix rspec integration so we can just run `rake` rather than `rspec spec`
- [x] Remove Mustache (Only `app/view/measurements/manifest` uses it)
- [x] Replace `unicorn` with `puma`
- [x] Replace `watchr` with `guard` + `guard-rspec` + others
- [ ] Ask for Sidekiq Pro license and use Sidekiq for importing (need to revisit deployment)

**Comment by matschaffer** [comment]
@evadne I noticed that the only bullet point not covered on #34 is a dataset to play with. Seems like this might also be covered of your mention of a meaningful seeds.rb.

Do you or @robouden have any current flow around getting a test data set loaded locally?

**Comment by matschaffer** [comment]
#178 covers the bump to latest rails 3. I tried ruby 2.2.2 but many gems were not happy with it so trying rails 4 now.

**Comment by Steven-Wright** [comment]
#182 configures CircleCI and Code Climate, working on New Relic.

**Comment by Steven-Wright** [comment]
Moving forward on #179 and #162 requires someone who understands the deployment process. Perhaps @nokton or @robouden can point us in the right direction.

**Comment by matschaffer** [comment]
I have dev access at least but we'll need @robouden for any prod deployments (as in #179).

For #162 things looked safe enough to push to dev but I'm unclear on how to verify if it's working as expected or not. Hoping @robouden can help there too since he was the PRs original author.

**Comment by Steven-Wright** [comment]
Implementing New Relic might easily facilitate something along the lines of #155

**Comment by Steven-Wright** [comment]
@matschaffer It appears to be running sucessfully. Getting monit and new relic going would give us some insight as to whether or not it was encountering issues.

It also gets back to the test coverage & accuracy point, as it stands now every flagged bug defeates the tests. Going through and fixing the test so they catch them could be more valuable than simply fixing the problems alone.

**Comment by eitoball** [comment]
I am closing this issue since it seems to be almost done.
