### ISSUE TITLE
Issues list needs massive clean up

### ISSUE THREAD

**Issue by seanbonner** [Safecast/safecastapi#171]
There are a number of 2 and 3 year old issues sitting in this list. Would appreciate people going through and either closing issues that have been resolved, merging similar issues, or bubbling up things still pending. Idea being when people want to help us they are faced with 3 years and 80+ issues and have no idea what is useful to look at first and give up right away. Would be good to get this into a much more workable list that people could look at and chip away at.

**Comment by matschaffer** [comment]
Just closing [everything not updated since 2014/01/01](https://github.com/Safecast/safecastapi/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+updated%3A%3C2014-01-01+) would get us down to 26 issues.

Happy to click the close button on your behalf but maybe someone like @seanbonner or @robouden should skim the subjects first to ensure there aren't any terrible glaring bugs in the list?

**Comment by seanbonner** [comment]
Unfortunately there are lots of glaring bugs on the list, so they need to be addressed not just closed.

**Comment by nokton** [comment]
Yes, lets not just close based on date. Why not use the prioritisation feature to create a backlog. You could put some lebels on it to sort items we have reviewed, versus items that need to be reviewed for inclusion in the backlog.

Pieter

**Comment by matschaffer** [comment]
I set up https://waffle.io/Safecast/safecastapi last week to at least keep an eye on the couple of things that were in-flight.

If folks are interested, it allows for drag-and-drop ordering as well as a differentiation between "Ready" and "Backlog".

**Comment by matschaffer** [comment]
I think we're getting there with the use of https://waffle.io/safecast/safecastapi - issue list is still long the "Ready" and "In Progress" labels from waffle are giving us a good place to focus.

I've also been doing some pruning during the monthly meetings and as I have time.
