### ISSUE TITLE
Add new index to rails schema

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#175]
This [was added to the prod db](https://safecast.slack.com/archives/api/p1432626644000158). Should probably get added to the app's schema definition as well.

```
CREATE INDEX idx_measurements_value_device_id_device_id_not_null ON measurements(value, device_id) WHERE device_id IS NOT NULL;
```

**Comment by Steven-Wright** [comment]
Adding the line to `schema.rb` is easy enough
`  add_index "measurements", ["value", "device_id"], :name => "idx_measurements_value_device_id_device_id_not_null"`

 If style counts for anything, I noticed that all of the other indices start with index as opposed to idx.

**Comment by matschaffer** [comment]
It's probably safe enough. I haven't had time look into whether or not we'll want to bump the version, make a migration, etc. to account for dbs that might still need the index applied (like the dev server for example).

**Comment by Frangible** [comment]
Note I also added an additional index due to a similar problem that led me to create the original in Mat's OP:
```
CREATE INDEX idx_measurements_captured_at_unit_device_id_device_id_not_null ON measurements(captured_at, unit, device_id) WHERE device_id IS NOT NULL;
```
This will also need to be included in whatever Ruby schema file.

**Comment by matschaffer** [comment]
I pulled the latest structure from prod when finishing #214 so we should be all set here.
