### ISSUE TITLE
Support for multiple sensors per device

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#187]
As covered in [Roundup #1](https://plus.google.com/u/0/events/cmfcpgh79pqjhrj7eq9vhr5hc7s) we have a number of devices (Air, Pointcast, Pocket) that sport more than a single sensor like the bGeigie.

We should have some support in the api for defining a device that has multiple sensors and key the measurements off of the sensor they were measured by.

One option for this was to create multiple devices for a single physical machine (one per sensor). This would avoid any large scale data model changes.

Another would be to alter the schema to accommodate the concept that a device has_many sensors.

**Comment by thinrope** [comment]
For the second option, just add a new class (sensor_group, metadevice, whatever) that keeps reference to a list of (current) device_ids=sensor_ids and some metadata.

**Comment by matschaffer** [comment]
Deferring this as we should really have a better story around how to use the air data (e.g., visualization) before we get too fixed about how to ingest it.

**Comment by nokton** [comment]
Agreed - I’m working on it with some other folks on that right now. What we have in the API will work fine for the first batch of air sensors (e.g. the structure used for pointcast)  to go online. Once we have data we can see how to make the next step.

**Comment by matschaffer** [comment]
https://github.com/safecast/ingest serves this need now, so closing this out. Over time we'll work on moving all data handling to that app since it has a flexible data model.
