### ISSUE TITLE
Support for multiple values per sensor

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#188]
As covered in [Roundup #1](https://plus.google.com/u/0/events/cmfcpgh79pqjhrj7eq9vhr5hc7s) we have a number of devices (Air, Pocket, 6D) that have sensors capable of reporting things like histograms.

We may be able to simplify the storage of this into a fixed set of "interesting" buckets such that each sensor type would always provide a fixed number of scalar measurements.

Getting this stored into the measurements table will take some exploration.

**Comment by thinrope** [comment]
Just to give you a sense of what spectrum looks like, think of say 4K integer array, integers being number of counts/channel. There is also metadata that goes with it (e.g. live duration, voltage used, calibration data, etc.). For a more graphical preview, have a look here:  http://gamma.tar.bz/spectra/#__spe%2F2015-03-25_-_Koriyama_parking.spe//0 (scroll down for more data)
In fixed sensors, I expect to be able to obtain one spectrum between 10min and an hour; many of the 4K channels will be zeros, some kind of compression is usefull. Currently I worked on simple RLE of the CSV that drops a spectrum from about 8KB to 1.2KB and is not very computationally expensive.
Additionally averaging across several channels/resampling can be used; combining spectra in time is generally preferred to loosing resolution, if we cannot afford lossless compression/storage.

**Comment by matschaffer** [comment]
Covered (at least for air data) by #205
