### ISSUE TITLE
Added devicetype_id to dev.safecast.org measurements table

### ISSUE THREAD

**Issue by robouden** [Safecast/safecastapi#192]
For dev only

**Comment by tamemotoakihiro** [comment]
OK.

2015/08/19 11:39、Rob Oudendijk <notifications@github.com> のメッセージ:

Just for testing

—
Reply to this email directly or view it on GitHub
<https://github.com/Safecast/safecastapi/issues/192>.

**Comment by matschaffer** [comment]
Closing as https://github.com/safecast/ingest handles this now
