### ISSUE TITLE
Adding Fields to measurements table Migration

### ISSUE THREAD

**Issue by robouden** [Safecast/safecastapi#200]
class AddDeviceTypeToMeasurement < ActiveRecord::Migration
    def change
       add_column :measurements, :devicetype_id, :string
    end
end

class AddStationToMeasurement < ActiveRecord::Migration
    def change
       add_column :measurements, :station_id, :integer
    end
end

class AddChannelToMeasurement < ActiveRecord::Migration
    def change
       add_column :measurements, :channel_id, :integer
    end
end

class AddSensorToMeasurement < ActiveRecord::Migration
    def change
       add_column :measurements, :sensor_id, :integer
    end
end

**Comment by matschaffer** [comment]
Closing this in favor of #205
