### ISSUE TITLE
Staging environment

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#211]
- [X] switch to api-staging.safecast.org cname
- [x] check if admin works
- [x] clear process for restore from prod data

**Comment by robouden** [comment]
Admin does not work

**Comment by robouden** [comment]
https://github.com/Safecast/safecastapi/wiki/Duplicate-data-from-production-to-staging-by-Cloud66

**Comment by matschaffer** [comment]
Staging does work it's just often too slow. See http://api-staging.safecast.org/admin/bgeigie_log for an admin page that will probably load.

Here's an pic to provide I did get it loading the home page once, but it's often > 60s which causes HAProxy to timeout:

<img width="1422" alt="screen_shot_2015-12-08_at_3_40_34_pm" src="https://cloud.githubusercontent.com/assets/690/11649420/20ae1584-9dc2-11e5-9911-4810c6d42e7d.png">
