### ISSUE TITLE
Provide API key via cookie-authed API

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#218]
This should make it easier for applications to snag the API key rather than scraping the HTML to get the currently logged in user id.

Since https://api.safecast.org/users/1.json already works, perhaps https://api.safecast.org/users/current.json makes sense.

**Comment by elafargue** [comment]
Example of endpoint: https://api.safecast.org/en-US/users/573  - if we can use a "current" instead of numeric ID, we're good...

**Comment by mcrollin** [comment]
This endpoint would be great to have! How do you suggest we would we authenticate?

**Comment by matschaffer** [comment]
@mcrollin for now I was thinking just a form encoded post to `https://api.safecast.org/users/sign_in` like you do today (probably, not sure about taking the locale out like that).

It'll give you a cookie back which you can then pass into something like `https://api.safecast.org/users/current.json`

**Comment by matschaffer** [comment]
If the cookie doesn't work another thought I had was allowing http basic auth but only to that endpoint.
