### ISSUE TITLE
HAProxy logs

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#220]
Would be good to know if we're seeing availability issues due to HAProxy marking backend hosts as "busy" - HAProxy logging should show that for us.

**Comment by matschaffer** [comment]
While we're in here we might want to figure out why the prod HAProxy isn't sending the right headers for rails to log the real client IP. In staging it's fine so there's likely some config discrepancy.

**Comment by matschaffer** [comment]
Closing this out since we probably don't need it until we're on AWS & ELB anyway.

**Comment by matschaffer** [comment]
Well so much for that.

We might need this after all. HAProxy doesn't terminate SSL so for this to work we'll either need to do that or set up https://www.haproxy.com/blog/using-haproxy-with-the-proxy-protocol-to-better-secure-your-database/ so the app can at least see the original IP via proxy protocol header.

I don't know if rails can use it or not but at least with it enabled we should be able to see original IPs of troublesome requests via tcpdump.

The issue we're facing at the moment which we could use this info for is that something is making these sorts of requests

```
[017a6930-1bcc-4dbc-a0c6-742d2ef3eafd] [162.243.100.197] Started GET "/measurements.json?page=52254&user_id=9" for 162.243.100.197 at 2018-01-17 04:46:19 +0000
[017a6930-1bcc-4dbc-a0c6-742d2ef3eafd] [162.243.100.197] Processing by MeasurementsController#index as JSON
[017a6930-1bcc-4dbc-a0c6-742d2ef3eafd] [162.243.100.197]   Parameters: {"page"=>"52254", "user_id"=>"9"}
``` 

and it's really bogging down the db.

**Comment by matschaffer** [comment]
Tried configuring the haproxy for proxy protocol, but no dice yet. In other news it looks like c66 might be able to do letsencrypt ssl termination at haproxy which would probably make things a little easier, but seems like this would (1) cause an interruption and (2) switch ssl providers which _could_ cause some trouble with clients. Though hopefully not.

**Comment by matschaffer** [comment]
Got it. The trick comes down to:

1. Enable support in nginx by specifying the 443 section as:
```
listen                    443 ssl proxy_protocol;
...
real_ip_header proxy_protocol;
```
2. Enable support in haproxy by adding send-proxy:
```
{% if ssl_termination != true %}
backend www_backend_ssl_443
	mode	tcp
	balance	{{ balance }}
	{% for server in servers %}
	server	web{{ forloop.index }} {{ server.ext_ipv4 }}:443 send-proxy
	{% endfor %}
{% endif %}
```

**Comment by matschaffer** [comment]
Once that's in place, `staging.log` shows my IP. So I'll set it up on production tomorrow.

**Comment by matschaffer** [comment]
Unfortunately prod LB is haproxy 1.4, which isn't capable of sending the client IP via proxy protocol.

According to cloud66 support, our best option is to delete the LB from cloud66 (but not from Digital Ocean), then have cloud66 create a new LB, then update the DNS record (mediatemple, 12h TTL) to the new LB.

Once traffic has moved over, we can remove the old LB on digital ocean.

**Comment by matschaffer** [comment]
I had rob move DNS for api.safecast.org and api-staging.safecast.org to be CNAMES to route53 in AWS. So the new setup is:

- `api.safecast.org CNAME api.safecast.cc`
- `api-staging.safecast.org CNAME api-staging.safecast.cc`

Still waiting for mediatemple's 12hr TTL to get things completely moved over, but I did manage a LB swap in staging tonight. Traffic just still is mostly coming through the old LB, but some stuff is coming via the new one as well.

So the process recommended by c66 support seems to work. And as a bonus the new LBs report client IPs via `X-Forwarded-For` and terminate SSL using a letsencrypt cert.

The process is:

* Note name and IP of current LB server
* Remove LB in c66
* Add new LB in c66
* Update safecast.cc DNS in route53 to point to new IP
* Wait for DNS resolution (in theory 1m, but best to wait a bit longer and watch for traffic from the old LB IP in the app logs)
* Remove the old LB server in digital ocean

**Comment by matschaffer** [comment]
Thinking I'll make the prod change Wednesday or so. Left a note [in slack](https://safecast.slack.com/archives/C026F2Q1U/p1516539988000089) regarding that.

There's a small possibility that the letsencrypt SSL termination in the new load balancer will throw off some older automation, but as mentioned in https://github.com/Safecast/safecastapi/issues/179, the current cert is already exposed, so probably better to stop using it anyway.

**Comment by matschaffer** [comment]
Alrighty, new LB is in place. I'll wait till then have rob clean up the old staging and prod LBs.

**Comment by robouden** [comment]
Will do tomorrow morning...
