### ISSUE TITLE
Remove rsync between app nodes during API data export jobs

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#221]
# Description

We have a number of API export jobs that run periodically.

![screen shot 2018-01-17 at 11 36 04](https://user-images.githubusercontent.com/690/35022870-797015d2-fb7b-11e7-882c-5461b2385876.png)

They correspond to:
- https://github.com/Safecast/safecastapi/blob/master/script/dump_clean
- https://github.com/Safecast/safecastapi/blob/master/script/dump_measurements
- https://github.com/Safecast/safecastapi/blob/master/script/dump_measurements_ios

As the last step, they all attempt to rsync the exported data to the other server. This makes server replacement require a bit of finagling which is not fun and won't be conducive to an AWS autoscaling setup.

Would be better to make these jobs export to S3 and have the app redirect the published URLs (`/system/(file name)`) to a public s3 object.

**Note:** while we're working on these scripts, we should probably add a `set -eo pipefail` to them. Currently there are cases (e.g., sqlite3 not being installed) where the export will fail but the job will still "succeed" as far as the exit code is concerned and we won't know about the failure until someone reports map problems.

## Background from issue when originally opened

I disabled this and got this worker error from dump_measurements_ios:

```
ssh: connect to host lion.api.safecast.org.c66.me port 22: Connection timed out 
rsync: connection unexpectedly closed (0 bytes received so far) [sender] 
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]
```

https://github.com/Safecast/safecastapi/blob/master/script/dump_measurements_ios#L66 seems to be a step to ensure the resulting file can be served from both app servers.

Seems like something we should look to push to s3 instead.

**Comment by matschaffer** [comment]
Ah. I think I might see what's happening. https://github.com/Safecast/safecastapi/blob/master/script/dump_measurements_ios#L66 seems to be a step to ensure the resulting file can be served from both app servers.

Seems like something we should look to push to s3 instead.

**Comment by thinrope** [comment]
I can probably work on that, but will need guidance...
My thoughts are that we can safely drop those, stuff an old copy of measurements.tar.gz in the new server and work from there. The data is only occasionally downloaded, so a few days delay is fine.
Basically, if that is the last thing holding the migration, just ignore it and let's work on in a new issue like "Provide snapshots of data for download". Once the dB is migrated, I'll work directly with it to achieve similar output.

**Comment by thinrope** [comment]
Hmm, I just found PR #532 merged... I guess that adds at least one user that "depends" on daily snapshots, may be we can deal with it directly (inform for prolonged maintenance)?
