### ISSUE TITLE
Staging map not working

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#226]

**Comment by matschaffer** [comment]
Seems to be working on http://api-staging.safecast.org/en-US/bgeigie_imports/20508

The couple test imports I see from Rob's account on staging show 0 measurements which I'm guessing is why the map isn't showing.

As to why they're showing 0 measurements? I'll consider than an issue for another day.

**Comment by robouden** [comment]
Maps do work correctly now..thanks
