### ISSUE TITLE
Add an Admin comment field on drives

### ISSUE THREAD

**Issue by elafargue** [Safecast/safecastapi#237]
Request by Azby: add a text field on drives for moderators to comment upon approval/rejection for traceability.

**Comment by robouden** [comment]
more request same idea..:

In API, next should be a simple button to reject, comment field (why) and email to submitter. Should have 	no impact on backend - will be great help. Submitter should also be allowed to reject own drive. Other 	one 	is to send an email if someone has uploaded but not submitted in 24h.
