### ISSUE TITLE
Add a 'reject' flag on drives

### ISSUE THREAD

**Issue by elafargue** [Safecast/safecastapi#238]
Request by @jam : add a way to reject drives - currently drives are either 'not approved' or 'approved', but there is no 'rejected' option.

**Comment by matschaffer** [comment]
Guessing #75 is sort of related here.

**Comment by jsidd** [comment]
Progress update - in my local environment, I was able to add the reject button and unreject button and hide the Submit for Approval when file is rejected accordingly. Going to 
add a tab with a simple form for moderators to send manual emails to file owner now.
![reject](https://cloud.githubusercontent.com/assets/3145723/15695068/63411aa8-27de-11e6-824b-558756fb47b9.png)
![unreject](https://cloud.githubusercontent.com/assets/3145723/15695069/643f9876-27de-11e6-8067-0c431969bdc0.png)

**Comment by robouden** [comment]
Very nice


Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> twitter:robouden <http://bit.ly/RAiSTC>

**Comment by robouden** [comment]
Did a test for importing log with latest build. But got error. 
"NoMethodError in BgeigieImports#show
Showing /Users/user/safecastapi/safecastapi/app/views/bgeigie_imports/_current_status.html.erb where line #2 raised:

undefined method `rejected?' for #<BgeigieImport:0x007ffde20c6b28>"
