### ISSUE TITLE
Consolidate MAPS + IMPORTS pages

### ISSUE THREAD

**Issue by sohlis** [Safecast/safecastapi#25]
- Kill "maps" and just use "imports"
- The arrows are too big, the map is too small, the arrows are not clickable
- show list in more informative manner - include description, drive actual date, description
- allow to sort drives by fields (date, city, etc)
- add search

**Comment by thinrope** [comment]
@sohlis So do you feel we can close this issue now?

**Comment by matschaffer** [comment]
Get the impression this portion of the site doesn't exist anymore. At least doesn't align with anything I've seen so seems closable.
