### ISSUE TITLE
Status label of Bgg Import not changing correctly [Unprocessed=>Processed=>Submitted=>Processed]

### ISSUE THREAD

**Issue by jsidd** [Safecast/safecastapi#255]
![label_status_bug](https://cloud.githubusercontent.com/assets/3145723/15663368/460a4c60-2735-11e6-8a9d-8b0c11220068.png)
Status label of Bgg Import not changing correctly [Unprocessed=>Processed=>Submitted=>Processed]
Example - this is a live file but it still says "Processed" (Right after saying "Submitted" for previous state)
https://api.safecast.org/en-US/bgeigie_imports/10757

**Comment by seanbonner** [comment]
Status label is not supposed to mimic the 6 steps below it, it's supposed to show binary of if a file has been processed or not. 6 step bar below is to show where in the moderation chain the file is.
