### ISSUE TITLE
Log subtype selection needs additional verbiage in UI

### ISSUE THREAD

**Issue by Frangible** [Safecast/safecastapi#270]
**Summary**

The current log subtypes have resulted in some degree of user confusion; eg, the incorrect selection of "Surface" instead of "Drive."  A single word likely cannot adequately describe this to the user, so per Pieter, in-line verbiage in the drop-down selection list and some help text should be added.  This issue will focus solely on the in-line verbiage, however.

**Steps to Reproduce**

1. Edit the metadata for an imported log, and click the drop-down list to select the subtype.
2. Note the displayed text.

**Expected Behavior**

When selecting the log subtype, a short descriptive text is present after the subtype.

Per Pieter, the drop-down list text should be:

* Drive (car, bike, walk, boat, terrestrial) 
* Surface (near immediate surface, alpha/beta activity~~, see help~~)  
 * *([NICK]: omit the help reference until an additional help view exists)*
* Cosmic (aircraft, balloons, rockets)

**Actual Behavior**

No descriptive text is present.

**Other**

It seems this is currently defined in:

https://github.com/Safecast/safecastapi/blob/master/app/views/bgeigie_imports/_edit.html.erb#L99

As: 
`:collection => %w(Drive Surface Cosmic None),`

But should be something like: 
`:collection => ("Drive (car, bike, walk, boat, terrestrial)", "Surface (near immediate surface, alpha/beta activity)", "Cosmic (aircraft, balloons, rockets)", "None"),`

However, that will need to be modified to only apply to the text label rather than the value.  I am uncertain of the syntax to accomplish this in Ruby.

**Comment by matschaffer** [comment]
Merged PR, pushing to staging

**Comment by matschaffer** [comment]
Staging looks good, going to prod

**Comment by matschaffer** [comment]
In prod, closing
