### ISSUE TITLE
Add ability to download drive log file in KML format from the drive page (request from volunteers in Fukushima)

### ISSUE THREAD

**Issue by nokton** [Safecast/safecastapi#277]

**Comment by matschaffer** [comment]
@nokton did the volunteers have any example documents we could use?

I'm sure we could do the transformations, but KML looks like a really flexible format so might be worth finding out more about just what the intended use is we can try to make sure our structure matches that.

**Comment by eitoball** [comment]
I wrote a simple script that converts bGeigie Import file to KML to learn about bGeigie import data and KML. [This map](https://www.google.com/maps/d/viewer?mid=1CIqDsjgvhxgpKQgmyQmpA8-CirM) is created from [this bGeigie Import](https://api.safecast.org/en-US/bgeigie_imports/10775).

Maybe, we can discuss how we should format based on this?

**Comment by robouden** [comment]
Eito-san

Nice. Did you have a look at the databot code at
https://github.com/Safecast/Databot?

regards
rob



Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> twitter:robouden <http://bit.ly/RAiSTC>

**Comment by nokton** [comment]
databot has the code to convert too - volunteers requested what databot does in the API (so when you hit download, you could have option to choose the format)

We could even include an option to download the PDF map of the drive like in databot

**Comment by eitoball** [comment]
@robouden 

> Did you have a look at the databot code at

No, I didn't know about the project. I checked code, and updated scriptand [map](https://www.google.com/maps/d/viewer?mid=1CIqDsjgvhxgpKQgmyQmpA8-CirM) (except name in uSv/h) . I am going to start to work on this feature.

**Comment by robouden** [comment]
Eito-san,

If you need more help let me know. I have also a standalone version that
Lionel made a few years ago.

regards
rob



Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> twitter:robouden <http://bit.ly/RAiSTC>

**Comment by nokton** [comment]
Databot is on Lionel's github repo: 
https://github.com/bidouilles/Databot

 Pieter
