### ISSUE TITLE
Add test for measurements coming in api-staging.

### ISSUE THREAD

**Issue by robouden** [Safecast/safecastapi#295]
Create test environment for testing data coming in from pointcast or other sensors for api-staging. So we can test the api before deployment on production.

**Comment by matschaffer** [comment]
Going to close this out. We sort of have this already thanks to api-staging.safecast.org.

We don't go as far as to send pointcast data to it, but we do cover a fair bit of that in integration tests.

My intent is that once we're on AWS it should open things up to more metrics to ensure ongoing staging functionality (via cloudwatch ELB metrics for example).
