### ISSUE TITLE
Change password does not work.

### ISSUE THREAD

**Issue by robouden** [Safecast/safecastapi#323]
In user/profile/change password does not work. Maybe related to the issue with IOS not being able to login. Maybe Eito-san can have a look?

**Comment by eitoball** [comment]
> Maybe related to the issue with IOS not being able to login.

I don't think that it is related.

> Maybe Eito-san can have a look?

See #324

**Comment by robouden** [comment]
Eito,

Thanks for the fix. I tested it on staging and works fine. Now deploying on
production.

regrads
rob



Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> twitter:robouden <http://bit.ly/RAiSTC>

**Comment by thinrope** [comment]
Is this critical issue still open? Or fixed by https://github.com/Safecast/safecastapi/pull/328

**Comment by robouden** [comment]
​Fixed by #328 as far as I tested it.

rob
​


Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> twitter:robouden <http://bit.ly/RAiSTC>
