### ISSUE TITLE
API display of measurement takes a jump forward in time

### ISSUE THREAD

**Issue by robouden** [Safecast/safecastapi#331]
This query works well:  http://dev.safecast.org/en-US/devices/2043926292/measurements?order=id+desc

include the "order=id+desc" it sorts properly, whereas if not include that the sort doesn't behave correctly.

**Comment by eitoball** [comment]
```
If the ORDER BY clause is specified, the returned rows are sorted in the specified order. If ORDER BY is not given, the rows are returned in whatever order the system finds fastest to produce.
```
(https://www.postgresql.org/docs/9.1/static/sql-select.html)

If `order` parameter is not specified, api will output whatever `SELECT` query returns. And, the result of `SELECT` query is "whatever order the system finds fastest to produce". In a sense, it is working correctly. But, I am not saying that this behavior is right.

I guess that api should order by primary key (which is usually `id` column) when no order is specified.

**Comment by matschaffer** [comment]
This is how the DB works, so seems like we can close this. If there's a specific use case for a page which require some default (e.g., by time) sorting, let's open a specific github issue for that.
