### ISSUE TITLE
Status metrics for fixed sensors

### ISSUE THREAD

**Issue by robouden** [Safecast/safecastapi#333]
Currently Pointcast and Simplecast both use devicetype_id for storing status of the devices. It would be beter to have a dedicated status field of the device.

**Comment by matschaffer** [comment]
from Nick in GTalk

```
{"captured_at":"2016-11-05T00:34:40Z","channel_id":null,"device_id":100049,"devicetype_id":"DeviceID:10004,Temperature:13.9,Battery Voltage:4.59,Fails:87,Restarts:83,FreeRam:53660,Last failure:,NTP count:2","height":535,"id":2354003,"location_name":null,"original_id":2354003,"sensor_id":null,"station_id":null,"unit":"status","user_id":9,"value":13.9,"latitude":34.4883,"longitude":136.165}
```

That's what Rob sent me as an example earlier.

**Comment by robouden** [comment]
Sample devicetype_id":"STATS:8d0h5m,101002,14,1,1"  currently in the measurements table

**Comment by matschaffer** [comment]
As we discussed a bit in the Nov 9 status meeting, I'm inclined to give this its own table & endpoint so we can do a simple time rotation on the data to avoid too much junk in the DB.

Maybe something like `/telemetry` or `/sensor_metrics` and have it save to a similar table.

Doing something like elasticsearch+kibana would be cool too, but I don't think I'd have bandwidth to get that set up until I get the AWS migration off my plate.

**Comment by matschaffer** [comment]
I'm gonna close this out since in my mind ingest is now the proper place for this sort of thing. It's a new DB & updated app so we can support jsonb and pretty much any arbitrary time series that anyone wants to send.

@robouden if you think we still need this or there's something we need to address for ingest, let me know.

**Comment by robouden** [comment]
ok.. seems fine for me.. Since we will use ttserve for sending data from Pointcast in the near future, we can redefine any data.
