### ISSUE TITLE
Update Ruby version

### ISSUE THREAD

**Issue by Morred** [Safecast/safecastapi#338]
At the moment we're using Ruby 2.1.10 (current stable is 2.4.0, I was able to update to 2.2.3 locally without having to fix/change anything). Any reasons why we should stick with 2.1.10?

**Comment by eitoball** [comment]
Not particular reason. I was kind of waiting for AWS migration. Would you like to submit PR to update ruby to 2.2.x?

FYI, I was updating ruby and rails in turn like ruby 2.0 -> rails 4.0 -> ruby 2.1 -> rails 4.1 -> (ruby 2.2 ?)

**Comment by Morred** [comment]
Yup, can do. Will also check which Rails version we can update to like this without running into immediate issues.
(Sorry for the late reply, was on vacation in Germany and travelled around a lot for friends and family stuff)

**Comment by eitoball** [comment]
> Yup, can do. Will also check which Rails version we can update to like this without running into immediate issues.

Please talk to @matschaffer when you update ruby. About Rails, we should be update to 4.2 without any issues. We need to ruby 2.2 or above to Update to 5.0, and we need some modifications.

**Comment by eitoball** [comment]
Closing since question has been answered.
