### ISSUE TITLE
Contributor Guide

### ISSUE THREAD

**Issue by paulca** [Safecast/safecastapi#34]
We need a contributor guide with tighter instructions on:

 - setting up development environment
 - getting tests runing
 - a sample data set to play with
 - a GitHub pull-request flow

**Comment by matschaffer** [comment]
We're 2 devs down using https://github.com/Safecast/safecastapi/wiki/Dev:-Setup-on-OS-X - gonna call that good enough to close this. We can address any shortcomings in that doc as we go.
