### ISSUE TITLE
Prototypical CSV -> s3 exporter

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#353]
We'll want to export query results from ingest's DB to s3. 

So I'll set up a worker with an example data dump.

This may also serve as a good cold storage mechanism from which to replay data later so /cc @eitoball so he can keep an eye on my progress as well.

## steps:

- [x] sqsd endpoint in app
- [x] worker env (dev)
- [x] output bucket
- [x] daily cron job to push all measurements to s3 as csv from the read slave
- [ ] worker env (prod)

**Comment by eitoball** [comment]
@matschaffer are you working on this? If not, I would like to try this with AWS Lambda.

**Comment by matschaffer** [comment]
Doo iit!

My plan for now was a beanstalk worker to run a script and push csv to s3.

Not actively in it yet though so if you've got plans make it happen. :)

**Comment by eitoball** [comment]
Created AWS Lambda function. See https://github.com/Safecast/ingest/tree/csv_exporter

**Comment by eitoball** [comment]
https://aws.amazon.com/jp/about-aws/whats-new/2016/11/aws-storage-gateway-provides-a-file-interface-to-objects-in-your-amazon-s3-buckets/

Can we use this? If can, we don't need extra worker or lambda function. We can mount S3 bucket via NFS, and write CSV to mounted directory.
