### ISSUE TITLE
On upload, height field is being truncated

### ISSUE THREAD

**Issue by seanbonner** [Safecast/safecastapi#36]
On the API upload page, Looks like entering a sensor height of "1.3 meters" results in "1 meter"

**Comment by thinrope** [comment]
@seanbonner Do you remember where you saw that?
Just a random example from my uploads shows correctly 1.5m : https://api.safecast.org/en-US/bgeigie_imports/13336

Please consider closing this.

**Comment by seanbonner** [comment]
This looks like a 3 year old issue that might have been fixed indirectly during some other update.
