### ISSUE TITLE
Unable to search using strings with accented characters

### ISSUE THREAD

**Issue by juhele** [Safecast/safecastapi#365]
Hi,
I recently found out that it is not possible to search (filter) data using strings with accented characters like our ě, š, č etc. 

For example - search:
https://api.safecast.org/en-US/bgeigie_imports?utf8=✓&q=Šik&approved=&by_user_id=671&uploaded_after=&uploaded_before=&by_status=&commit=Filter
returns no results.

Although:
https://api.safecast.org/en-US/bgeigie_imports?approved=&by_status=&by_user_id=671&commit=Filter&order=created_at+asc&q=Václav&uploaded_after=&uploaded_before=&utf8=✓

proves, that there are several measurements by "Václav Šik".
I agree this is minor issue but sometimes annoying as we often send "personal" links to people who had borrowed bGeigie from our institute.

regards

Jan

**Comment by eitoball** [comment]
This is because API lowers case when searching (https://github.com/Safecast/safecastapi/blob/master/app/models/bgeigie_import.rb#L32-L38) and `String#downcase` in ruby 2.1 is not working well.

On ruby 2.1.10:

```
$ ruby -ve "puts 'Václav Šik'.downcase"
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-darwin16.0]
václav Šik
```

On PostgreSQL 9.5.5:

```
psql=# select lower('Václav Šik');
+--------------+
| lower        |
+--------------+
| václav šik |
+--------------+
1 rows in set (0.01 sec)
```


This has been fixed since ruby 2.3 (or 2.2?).

```
$ ruby -ve "puts 'Václav Šik'.downcase"
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
václav šik
```

**Comment by juhele** [comment]
thanks much for letting me know. Works OK with lowercase letters.

**Comment by eitoball** [comment]
It should work now since API server uses ruby 2.7.
