### ISSUE TITLE
Small AI setup with AWS ML for analyzing data to have an extra auditor for the bGeigie logs .

### ISSUE THREAD

**Issue by robouden** [Safecast/safecastapi#380]
Would be great if we could automize the approval process by training a small AI neural network with back propagation on the past approved logs as a training set. Eventually having the AI do all the work, if proven reliable. That would release the moderator for their tasks.

**Comment by eitoball** [comment]
At this moment, there are only 20 bGeigie imports. It is hard to create data set...

**Comment by robouden** [comment]
But we can take the data from the bGeigie logs on S3?

**Comment by eitoball** [comment]
Yes. What I meant was that I cannot create data set to **train** model. I don't think that 20 rejected imports are enough.

**Comment by nokton** [comment]
There are more waiting for approval - just filter drives “submitted” and not approved beyond a week ago or so

**Comment by Lugulbanda** [comment]
i wounder how u get enough declined map uploads, if they get edited to fit if some anomalys show up, how many people do the approving atm, sometimes a map goes instant to live, sometimes it takes Days, are u allready working with the AI, how many people do the aprovement and whats the normal acceptance time für ul maps ? speeding up the prozess for data without anomalys would be nice to...

**Comment by Lugulbanda** [comment]
thx for the onmouseover text, btw i figured out that the high blibs in the ios app, can be avoided if u start the app, and let ~10 measurements run by and then press the second start button for write data.. if iam not i a hurry and have the time i allways get measurements without the elevated blibs on the start... i only want to check if the high blib is only from the ios app or from the nano UL File.

**Comment by matschaffer** [comment]
Closing this down until we have some better ideas on how to actually train an approval/rejection model. So far rejections have been so minimal we may be better off with just flagging statistical criteria instead (e.g., N standard deviations away from drive average)
