### ISSUE TITLE
Reject w/o metadata

### ISSUE THREAD

**Issue by seanbonner** [Safecast/safecastapi#407]
Currently in order to reject a drive it requires metadata to have been added, however one reason for rejection is lack of metadata and often these logs are missing all the info, so a moderator has to go and fill out all the info boxes with "none" or something then save it before they can reject it. Should be able to reject immediately.

**Comment by matschaffer** [comment]
Looks like the conditional on https://github.com/Safecast/safecastapi/blob/master/app/views/bgeigie_imports/_head.html.erb#L8 should be tweakable to allow this.

Probably makes sense to move it into a `BgeigieImport#rejectable?` method as well since it's getting pretty long.

**Comment by eitoball** [comment]
It should be able to reject imports without metadata. If you need to fill metadata to make reject button on import detail page, #460 should display reject button on import detail page even if import has no metadata.

**Comment by matschaffer** [comment]
@eitoball so the action works, but I think maybe something in the UI is hiding it. For example here's a upload I did but never added metadata for. I'm logged in as an admin but there's no reject as far as I can see.

https://api.safecast.org/en-US/bgeigie_imports/22730

![screen_shot_2018-06-11_at_8_44_47](https://user-images.githubusercontent.com/690/41207632-06f9c1a6-6d54-11e8-9fb7-8cd33ffdc890.png)

And it shows up in the "not approved" queue.

https://api.safecast.org/en-US/bgeigie_imports/not_approved?page=8

![screen_shot_2018-06-11_at_8_45_35](https://user-images.githubusercontent.com/690/41207636-15bd27c8-6d54-11e8-934f-25a637be9100.png)

**Comment by eitoball** [comment]
>  but I think maybe something in the UI is hiding it.

@matschaffer Yes, it is. #460 needs to be merged to show "Reject" button. I thought that I mentioned about that in description of #462.

**Comment by matschaffer** [comment]
Ah, thanks. Guess I missed that detail. Merged #460 now and will get that pushed out.
