### ISSUE TITLE
Sorting on Users is wrong

### ISSUE THREAD

**Issue by seanbonner** [Safecast/safecastapi#432]
Similar to:
https://github.com/Safecast/safecastapi/issues/92

But more significant, trying to sort Users by ID or Name works, but sorting by Number of Measurements (which is the leaderboard thing that should perhaps be the default) doesn't work at all.

https://api.safecast.org/en-US/users?order=measurements_count+asc

**Comment by seanbonner** [comment]
Similar problems on the Devices sorting in fact, so maybe one problem causing everything?
https://api.safecast.org/en-US/devices?order=id+asc

**Comment by matschaffer** [comment]
@eitoball do you remember if we bumped kaminari at some point? Wondering if the sort params might have changed

**Comment by eitoball** [comment]
It hasn't changed. I haven't looked up commit log, but currently users can be sorted by only name. I am  working on user.

**Comment by eitoball** [comment]
It seems that it is sorting in some order I don't know (probably order of `measurements_count` in `users` table) since list of users changes when I click "Number of Measurements" header. But, it seems that `measurements_count` is not updated properly.

**Comment by matschaffer** [comment]
I did a full reset of user.measurements_count caches.

Not sure why they'd be off to begin with, but our postgres hasn't had the best love and care over the years so could be something got a little out of whack.

Now that it's fixed trying to order descending will timeout due to some method stubbing that probably worked when we were in the <10M measurements, but definitely is too slow today. The above PR should fix that.

**Comment by matschaffer** [comment]
Should be all set for https://api.safecast.org/en-US/users?order=measurements_count+desc

Looks like the device sorting is still not right so not the _same_ problem but possibly related.

**Comment by matschaffer** [comment]
For future reference this worked for resetting all the user caches and only took a few minutes.

```
User.all.each { |u| User.reset_counters(u, :measurements); sleep 0.5 }
```

**Comment by matschaffer** [comment]
Did the same operation on devices which seemed to get that happy too

```
Device.all.each { |d| Device.reset_counters(d, :measurements) }
```

I also had to remove a duplicated id=108 row from the staging db then add the primary key for the tabl. How it was missing I have no idea, but at least it's fixed now. And that part wasn't broken in prod... *phew*

Should be all set. Thanks for spotting the issue @seanbonner and the underlying data oddity @eitoball !
