### ISSUE TITLE
Set up restore of prod DB to RDS

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#433]
Was talking with Eito tonight and realized it'd be good to have a restored copy of the c66 data base to RDS. Doesn't have to be live yet, but it would make poking at data easier and also give us a good test bed to ensure the AWS deployment works.

**Comment by matschaffer** [comment]
Looks like this might be useful again in service of https://github.com/kevinyang372/Safecast_api - moved into inbox for comment in this week's meeting.

**Comment by matschaffer** [comment]
Tried this last night. It starts off at a good clip but then something is causing performance to tail off pretty bad.

Network on EC2 instance handling transfer
![screen shot 2018-08-11 at 8 59 58](https://user-images.githubusercontent.com/690/43985766-ff2cb16a-9d44-11e8-9914-29ab9ede647c.png)

Write ops on RDS
![screen shot 2018-08-11 at 9 00 19](https://user-images.githubusercontent.com/690/43985768-067f5c74-9d45-11e8-87d5-d720c84447f8.png)

Seems like it could take days to finish at this rate so thinking I'll try dumping to an EBS disk first and see what perf is like. That should at least prove or help rule out RDS itself as the bottleneck.

**Comment by matschaffer** [comment]
Nearing 24h and still only showing 11GB as the most progress. Gonna cancel and start a dump to EBS tonight and see if that does any better.

```
 33478 | public             | bgeigie_logs               |            0 | 22052896768 |  9769598976 |        8192 | 12283289600 | 21 GB      | 9317 MB    | 8192 bytes | 11 GB

```

**Comment by matschaffer** [comment]
<img width="887" alt="screen shot 2018-08-11 at 22 00 24" src="https://user-images.githubusercontent.com/690/43991975-fce30888-9db1-11e8-9fcf-9f71a5ab619d.png">

Initial metrics look good and we're already at 1G after about a minute into the transfer. Will continue to monitor. Thinking we may want to use both ec2 and rds instances will fairly high I/O ratings for the initial load then scale back as required.

**Comment by matschaffer** [comment]
Network bytes throughput is looking a lot more sustained. 4.3G so far.

Straight to RDS:
<img width="876" alt="screen shot 2018-08-11 at 22 24 12" src="https://user-images.githubusercontent.com/690/43992154-533c8094-9db5-11e8-8d4a-ce4a0f0690d8.png">

To EBS:
<img width="878" alt="screen shot 2018-08-11 at 22 24 21" src="https://user-images.githubusercontent.com/690/43992157-5a13e40c-9db5-11e8-9b47-40c61182163d.png">

I'm seeing sustained ~70Mbps inbound now, but the worker instance m3.medium is at 100% cpu, so seems like we could maybe do better with more cores (https://blog.flux7.com/benchmarking-analyzing-aws-m3-instances-for-performance-bandwidth reports 391Mbps for m3.medium). iostat is showing very low utilization for the EBS volume.

Given this I've upgraded the DB to an db.m4.xlarge (16GB ram, 4 cores, high network).

I'll do the same with the transfer instance and load the EBS dump into that to see what the perf is like there. 

Current rates seem to indicate we can transfer the DB in about 3 hours, which I'd be happy with but maybe we can do a little better on the m4.xlarge.

**Comment by matschaffer** [comment]
Dump "finished" in about an hours but resulting file was only 9.5GB so not sure if it's right.

Attempting an import into the newly embiggened RDS instance. Write iops look good so far, but will know for sure once it finishes and I can see what's in the dump.

**Comment by robouden** [comment]
Matt,

Great progress.
Maybe 9.5 gb is correct.

regards
rob



Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> linkedin:robouden
<https://www.linkedin.com/in/roboudendijk>

**Comment by matschaffer** [comment]
Based on https://www.fittedcloud.com/blog/is-it-possible-to-use-ebs-gp2-instead-of-io1-achieve-same-performance-and-save-50/ I'm going to update the RDS instance to a 2TB gp2. Seems like that might give us 6000 iops for $200/mo (vs $400 for piops). I'll plan to scale it back down after a few days of course.

**Comment by matschaffer** [comment]
```
[ec2-user@ip-172-31-1-158 dump]$ time pg_restore     --dbname=safecast     --table=admins     --table=bgeigie_logs     --table=configurables     --table=delayed_jobs     --table=devices     --table=drive_logs     --table=ioslastexport     --table=maps     --table=maps_measurements     --table=measurement_import_logs     --table=measurement_imports     --table=measurements     --table=rails_admin_histories     --table=schema_migrations     --table=users     --data-only --format=custom db-prd-c66-postgres-dump.pgdump
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 4093; 0 18595 TABLE DATA devices safecast
pg_restore: [archiver (db)] COPY failed for table "devices": ERROR:  duplicate key value violates unique constraint "devices_pkey"
DETAIL:  Key (id)=(108) already exists.
CONTEXT:  COPY devices, line 181
pg_restore: [archiver (db)] Error from TOC entry 4105; 0 18642 TABLE DATA measurements safecast
pg_restore: [archiver (db)] COPY failed for table "measurements": ERROR:  duplicate key value violates unique constraint "measurements_pkey"
DETAIL:  Key (id)=(51764662) already exists.
CONTEXT:  COPY measurements, line 34892863
pg_restore: [archiver (db)] Error from TOC entry 4107; 0 18650 TABLE DATA schema_migrations safecast
pg_restore: [archiver (db)] COPY failed for table "schema_migrations": ERROR:  duplicate key value violates unique constraint "unique_schema_migrations"
DETAIL:  Key (version)=(20111123174941) already exists.
CONTEXT:  COPY schema_migrations, line 1
WARNING: errors ignored on restore: 3

real    268m2.937s
user    4m17.104s
sys     1m43.564s
```
load on 2000gb m4.xlarge rds from m3.medium ec2 instance

**Comment by matschaffer** [comment]
Unfortunately after the copy I get no measurements, presumably due to the key error:

```
safecast=> select count(*) from measurements;
 count
-------
     0
(1 row)
```

Devices shows the same behavior. What's more, checking device id=108 on the main db only shows one row.

```
safecast=# select * from devices where id = 108;
 id  |  manufacturer  |     model     | sensor |         created_at         |         updated_at         | measurements_count
-----+----------------+---------------+--------+----------------------------+----------------------------+--------------------
 108 | GQ Electronics | GMC-300E Plus | M4011  | 2015-02-07 12:47:40.555464 | 2015-02-07 12:47:40.555464 |             488570
(1 row)
```

http://www.postgresql-archive.org/Duplicate-rows-during-pg-dump-td5871316.html seems to indicate this likely due to the same index corruption @thinrope brought up. Still unclear on how best to resolve it, but I'll keep working on it.

Will scale things back tonight and plan to work on the `schema_migrations` table since it should be quite small and also exhibits the duplicate key problem.

**Comment by matschaffer** [comment]
Interestingly enough, `schema_migrations` has the right number of rows on both dbs.

```
safecast=# select count(*) from schema_migrations;
 count
-------
    71
(1 row)
```

🤞 that my I can reproduce the error with just the schema_migrations table.

**Comment by matschaffer** [comment]
Heh. Also a nice learning, apparently you can't downsize an RDS disk, so the idea of upscaling for the initial transfer is out. Will have to experiment with provisioned iops then moving to gp2 as a possible solution.

**Comment by matschaffer** [comment]
So I figured out that my `schema_migrations` problem is because beanstalk was trying to run migrations. The `devices` ID collision appears to be real though. I can see 108 duplicated in the output of `copy devices to stdout;` on the main db.

**Comment by matschaffer** [comment]
Alrighty, that did the trick and let me clean up the 5 rows duplicated rows:

```
    id    |    ctid     |    ctid
----------+-------------+-------------
 51764664 | (674466,36) | (674466,99)
 51764662 | (674466,32) | (674466,43)
 51764666 | (674466,40) | (674472,2)
 51764663 | (674466,34) | (674466,60)
 51764665 | (674466,38) | (674472,1)
(5 rows)
```

**Comment by matschaffer** [comment]
Also tested gp2 -> piops conversion, but looks like there's a 6 hours storage optimization phase.

Will see what happens tomorrow going piops -> gp2. Might be simpler/cheaper to take the hit on import time running with gp2.

**Comment by matschaffer** [comment]
About to try a db load:

worker: m4.xlarge
db: m4.2xlarge, 300gb, 3000 piops

I still get some errors when doing `bundle exec rake db:structure:load` so not sure if the final DB will be functional but it should at least give us an idea of how long it takes to load the data in this configuration and how long it takes to get the piops back to gp2.

Errors are:
```
NOTICE:  extension "postgis" does not exist, skipping
DROP EXTENSION
NOTICE:  schema "postgis" does not exist, skipping
DROP SCHEMA
CREATE EXTENSION
psql:/var/app/current/db/structure.sql:34: ERROR:  must be owner of extension plpgsql
CREATE EXTENSION
psql:/var/app/current/db/structure.sql:48: ERROR:  must be owner of extension postgis
WARNING:  no privileges were granted for "geometry_columns"
GRANT
WARNING:  no privileges were granted for "spatial_ref_sys"
GRANT
```

This is using https://github.com/matschaffer/safecastapi/blob/beanstalk-deployment/db/structure.rds.sql.patch which I'd done some rds-specific changes for. Could be I need to revisit the structure.sql for RDS compatibility again.

**Comment by matschaffer** [comment]
Transfer in progress, going about 10MB/s as shown via the worker instance's `iftop -B` which is what I was getting before. Will check back in on CPU, network and iops metrics in 20m to see how things are going. Last time the transfer took ~4.5 hours so guessing this will be similar or maybe a little faster.

**Comment by matschaffer** [comment]
A little over 5 hours in. Still going, no errors so far. Write iops are looking real nice now around the provisioned 3000 /s if a little bumpy starting out.

<img width="488" alt="screen shot 2018-08-14 at 14 51 28" src="https://user-images.githubusercontent.com/690/44073946-9e3215be-9fd1-11e8-8c85-dff972cd3e84.png">

DB memory & CPU look fine - could probably use a smaller DB instance for this so long as network throughput was at least moderate.

<img width="900" alt="screen shot 2018-08-14 at 14 52 44" src="https://user-images.githubusercontent.com/690/44073988-ca504cb0-9fd1-11e8-9d4f-79d3ee5c4cc1.png">

<img width="894" alt="screen shot 2018-08-14 at 14 52 52" src="https://user-images.githubusercontent.com/690/44073995-d167555c-9fd1-11e8-911b-a8d059f68ff0.png">

CPU and network for the worker is also quite low:

<img width="898" alt="screen shot 2018-08-14 at 14 55 08" src="https://user-images.githubusercontent.com/690/44074078-2571d87a-9fd2-11e8-97cc-335dec872e7d.png">
<img width="889" alt="screen shot 2018-08-14 at 14 55 19" src="https://user-images.githubusercontent.com/690/44074079-25b0f280-9fd2-11e8-8a48-dd573c744c53.png">

So seems like the main bottleneck in the transfer is the DB iops. Hopefully conversion from piops to gp2 doesn't take too terribly long. If so we might want to do this transfer with even 6000 provisioned iops and smaller instance sizes.

**Comment by matschaffer** [comment]
https://stackoverflow.com/a/48209049/69002 seems to support this citing a figure as high as 40k iops.

I'll see what tuning to 10k mid import does. :)

**Comment by matschaffer** [comment]
Ah. Looks like I have to wait anyway. The instance is listed as "available" but guess there's a 6 hour cool down on storage modifications regardless. Will check back tonight and pump the iops if the transfer is still ongoing.

```
Storage modifications on this instance are not currently available because of one of the following reasons:
You have recently performed a storage scaling operation on this database instance. Please wait 6 hours from when storage optimization was completed.
```

**Comment by robouden** [comment]
Great!!



Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> linkedin:robouden
<https://www.linkedin.com/in/roboudendijk>

**Comment by matschaffer** [comment]
The import finished in just under 9 hours. This time with no errors:
```
[ec2-user@ip-172-31-2-5 ~]$ time \
>   pg_dump \
>     --host=localhost --port=15432 \
>     --table=admins \
>     --table=bgeigie_logs \
>     --table=configurables \
>     --table=delayed_jobs \
>     --table=devices \
>     --table=drive_logs \
>     --table=ioslastexport \
>     --table=maps \
>     --table=maps_measurements \
>     --table=measurement_import_logs \
>     --table=measurement_imports \
>     --table=measurements \
>     --table=rails_admin_histories \
>     --table=schema_migrations \
>     --table=users \
>     --data-only --format=custom |
>   pg_restore \
>     --dbname=safecast \
>     --data-only --format=custom


real    526m48.992s
user    27m30.432s
sys     0m50.056s
```

And I can see measurements as well

```
safecast=> select count(*) from measurements;
   count
-----------
 102656623
(1 row)
```

So a big step in the right direction. I'm now converting the piops drive to a gp2 drive while counting the metrics table in a loop.

This should let us see if there's any notable period of performance drop during the conversion. If it stays basically consistent I think we can use the strategy of a very highly provisioned piops drive (maybe ~40k) for import, get things basically working, then switch to gp2.

I suspect under normal operation the piops will be of fairly little use since the gp2 gives us up to 30m of 3k iops included in the base cost of the drive.

**Comment by matschaffer** [comment]
Looks like we've reached the storage-optimization phase without any noticeable query impact. Will check on it again tomorrow.

**Comment by matschaffer** [comment]
![screen shot 2018-08-14 at 21 53 29](https://user-images.githubusercontent.com/690/44092807-82bf48fc-a00c-11e8-9022-865c0b05f133.png)

Also worth noting that memory usage is still quite low with only ~10gb used. Wondering if the 32g on DO is basically overscaled from the problems we were having with the bgeigie show page.

**Comment by Lugulbanda** [comment]
Hi,
how about minimize the Traffic there, by only show all the data if someone is interested in it, 
most users first only want to see theyr own uploads, there is alot of unnessesary Traffic, cuz everyone sees allways the hole world dataset from all...

 

best wishes

Frank


Gesendet: Dienstag, 14. August 2018 um 14:54 Uhr
Von: "Mat Schaffer" <notifications@github.com>
An: Safecast/safecastapi <safecastapi@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [Safecast/safecastapi] Set up restore of DB backup to RDS (#433)




Also worth noting that memory usage is still quite low with only ~10gb used. Wondering if the 32g on DO is basically overscaled from the problems we were having with the bgeigie show page.

**Comment by matschaffer** [comment]
RDS is back on gp2 and I didn't notice any slow down of my measurement count queries during the process. 

Going to scale this RDS back to a t2.medium so it can hang around for some app-level testing w/o breaking the bank.

**Comment by matschaffer** [comment]
@Lugulbanda we're forklifting between cloud providers. Once it's done the original database will be decommissioned so can't be selective based on what someone is interested in.

That being said this process has reminded me that we should probably re-discuss archiving measurements sometime in the next year or so.

Probably don't need to keep all measurements for all time "hot" in postgres. But architecting that while retaining the ability to query longer historical data is definitely beyond the scope of this github issue.

**Comment by nokton** [comment]
How are you doing this - replication or parsing in data into an empty database?

**Comment by matschaffer** [comment]
dump/restore - https://github.com/Safecast/safecastapi/issues/433#issuecomment-412860104 has the full command
