### ISSUE TITLE
Switch ingest to use uri-based device IDs

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#436]
Ray switched up ttserve to publish a field like `safecast:DDDD`. We should switch ingest to key off that as well.

See https://docs.google.com/document/d/1FkqMgRsogaSuBL5PjS9NXkYBMQtaEuHOIDR2h9bC3cI/edit for details on ids

**Comment by matschaffer** [comment]
![kibana](https://user-images.githubusercontent.com/690/37378050-e81ba714-2770-11e8-9271-49cb15790f5d.png)

**Comment by eitoball** [comment]
@matschaffer 

Do you want to store this `device_urn` as is, or break it into two parts like `safecast` and `DDDD` and store them into two separate columns?

**Comment by matschaffer** [comment]
@eitoball I think as-is is probably the way to go for now. Then we can defer any decisions on how to split it up (e.g., enum & string, enum & bigint) until we have a good case for particular column types.
