### ISSUE TITLE
json schema required

### ISSUE THREAD

**Issue by sarveswaran-m** [Safecast/safecastapi#440]
Hi,

Am trying to implement a RESTful client to consume from safecast API.
Where can I find the json schema for request/response objects in the URI?
Tried looking in to safecastapi source code.
Could not find any .json file there.

**Comment by thinrope** [comment]
I don't think we have a ["JSON schema"](http://json-schema.org/) per se (i.e. machine readable definition of the interface), but have you looked at the documentation at https://api.safecast.org/en-US/home ?

**Comment by sarveswaran-m** [comment]
Yes, I am referring to the API home and it explains the available URIs & resources.
However, it does not discuss request/response json body and attributes.
Following is a sample measurement received from safecast server:

> {"id":107417210,"user_id":759,"value":46.0,"unit":"cpm","location_name":null,"device_id":100092,"original_id":107417210,"captured_at":"2018-03-25T00:00:02.000Z","height":67,"devicetype_id":null,"sensor_id":null,"station_id":null,"channel_id":null,"latitude":37.32925,"longitude":140.978431}

The type of each attribute and its purpose should be known in-order to unambiguously parse and extract information. While this can be inferred from the response, some are open to interpretation:
For eg, what does original_id refer to? what is the expected type/format of captured_at? Is station_id an integer or string? what is the data type of devicetype_id and how it has to be interpreted ("devicetype_id":"DeviceID:40,Temperature:14.5,Battery Voltage:5.08,Fails:2289,Restarts:726,FreeRam:53660,Last failure:,NTP count:2")? etc

Also, schema will be helpful to auto-generate RESTful client. 
Let me know how people are consuming from the API today and what your recommendation is?

**Comment by thinrope** [comment]
Yes, I totally agree, but at present this information is not available, AFAIK (I am not versed in Ruby and haven't played with the code much)...

I guess the best you can get is to dig into the database schema (and hoping that there is not much transformation in the Ruby code), e.g. https://github.com/Safecast/safecastapi/blob/master/db/structure.sql#L451

>what is the data type of devicetype_id and how it has to be interpreted ("devicetype_id":"DeviceID:40,Temperature:14.5,Battery Voltage:5.08,Fails:2289,Restarts:726,FreeRam:53660,Last failure:,NTP count:2")?
>
This is some temporary glue that was put, see issue #333 for discussion.

**Comment by matschaffer** [comment]
@eitoball are you familiar with anything we could do to embed this sort of api documentation info into the app itself?

Thinking something sort of like https://swagger.io/ must be available in the rails world.

**Comment by eitoball** [comment]
https://github.com/fotinakis/swagger-blocks I am thinking of using this for my work.

**Comment by matschaffer** [comment]
Closing out as #449 is merged. I'll get it to staging/prod sometime later today.

**Comment by matschaffer** [comment]
Ah right, just Users so opening back up for other models.

**Comment by matschaffer** [comment]
@sarveswaran-m that's the measurements json you're looking at right? @eitoball has annotated the `User` model so far so we should be able to have you covered once `Measurement` is annontated.

See https://api.safecast.org/api_docs.json for the definition and you can use https://editor.swagger.io/ to generate a client if you like.

**Comment by sarveswaran-m** [comment]
@matschaffer  Yes, this works well.
I generated a RESTful client in Java & used it to get all users.

However, `/users` is the only path available from api URI now.
We should make all supported paths(measurements, bGeigie imports, devices, etc) with filtering options available over swagger so that JSON schema would be available for those too.

**Comment by matschaffer** [comment]
@sarveswaran-m https://github.com/Safecast/safecastapi/pull/451 adds the measurements API as well. We'll close this issue once that's rolled out unless you need any other APIs covered.

**Comment by matschaffer** [comment]
Pushed this out to prod just now. Check out https://api.safecast.org/api_docs.json or feed it into https://editor.swagger.io/ if you need a client lib.
