### ISSUE TITLE
Use cases under consideration

### ISSUE THREAD

**Issue by sarveswaran-m** [Safecast/safecastapi#441]
Map based rendering of radiation information is quite nice and useful.
However, I am trying to identify other ways in which the data-set can be put to use and try implementing some.

Over the years the safecast team would have received many user-requests and considered certain use cases.
For eg, the provision to query and plot radiation information over a period of time to understand the long term trend. It would be great if someone can list of use-cases that safecast is considering or would like to see implemented.

NB:
I am planning to scrap data from safecast and experiment with use-cases in seperate code-base.
Will not be disturbing safecastapi code-base.

**Comment by matschaffer** [comment]
I think page 1 of https://docs.google.com/presentation/d/18RDRvmfqSg3fvxhU4Aw4yKs_9OdHCTBfR-Ace7KrmpI/edit probably covers the basics here.

It's not a list exactly but it calls out the actors we have in mind that we're trying to provide services for.

That beings said I don't think anyone at safecast could give you a comprehensive list. I'm sure there are great use-cases that none of us have considered yet.
