### ISSUE TITLE
RESTful URI serves HTML payload instead of JSON

### ISSUE THREAD

**Issue by sarveswaran-m** [Safecast/safecastapi#442]
When the following query is given to fetch user detail, the server returns a HTML response.
The expected response is user detail as json.

Request : 

> GET https://api.safecast.org/users/574

Following is the response : 
```

<!DOCTYPE html>

<html>
  <head>
<script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"611fd51d6a","applicationID":"10580222","transactionName":"dF8LREAKDV8BSxZMS1JCFh9BDQ5E","queueTime":0,"applicationTime":34,"agent":""}</script>
<script type="text/javascript">(window.NREUM||(NREUM={})).loader_config...................
.........................
  </head>
  <body data-spy="scroll" data-target=".doc-nav">
    <div class="container">
........................
    </body>
</html>
```
**NB:**
Use the online restful client tool @ [resttesttest.com](https://resttesttest.com/) to query.

**Comment by eitoball** [comment]
Our default response in text/html. Please specify `Accept: application/json` in request header. Please see #444
