### ISSUE TITLE
getting measurement_import_id

### ISSUE THREAD

**Issue by fobrs** [Safecast/safecastapi#445]
Hi,
Using the json REST api, I'm trying to get the measurement_import_id from a measurment id. I've looked at the sources, but cannot figure it out. The HTML page for a measurement id does show the Measurement Import! The json output doesn't. Am I doing something wrong?

**Comment by eitoball** [comment]
You aren't doing wrong. There is no `measurement_import_id` in output of `GET /measurements/:id.json`. May I ask why you want to get `measurement_import_id`?

**Comment by fobrs** [comment]
Because, like you, I want to show the original import log file, where the data point is based on.
Now I use this:
`https://api.safecast.org/en-US/measurements?captured_after=2018-03-26T12:49:52.9000Z&captured_before=2018-03-26T12:49:53.100Z&utf8=%E2%9C%93&user_id=1544&format=csv`
That returns me the measurement_import_id in the 12th CSV field. But that's a bit clumsy, because I need to identify the point by it's user_id and the time stamp, which is unique because a bGeigie cannot measure two points at once.
In my app 'Radiation Explorer for Safecast Data' for Windows 10, I would like to click on a data point from a CSV file and then show the all the points from the original LOG file.

**Comment by eitoball** [comment]
@fobrs 

You should get `mesurement_import_id` in `GET /measurements/:id.json` call. Please try it.

**Comment by fobrs** [comment]
I've seen it already and using it since a few days in my 'Radiation Explorer for Safecast Data' Windows 10 app. In the next version it will be used to display all the LOG data after clicking on a single data point.
Thanks!!
