### ISSUE TITLE
Add an API for automation of BGeigie data measurement file uploads.

### ISSUE THREAD

**Issue by lbrichards** [Safecast/safecastapi#453]
At present it is possible to automate parts of the login / upload / submission process using web-scraping tools such as selenium.  See the attached example.

[safecast2.py.zip](https://github.com/Safecast/safecastapi/files/1965939/safecast2.py.zip)

An extract showing how I currently automate login is shown here:

```python
def login(browser):

    browser.get(URL)
    delay = 5 # seconds
    t1 = time.time()
    try:
        myElem = WebDriverWait(browser, delay).until(
        EC.presence_of_element_located((By.ID, 'user_email')))
        print("Page is ready!")
    except:
        pass
    t2 = time.time()
    print('loading took {:0.2f} seconds'.format(t2-t1))
    email_field = browser.find_elements_by_id(
        'user_email')[0]
    pwd_field = browser.find_elements_by_id(
        'user_password')[0]
    login_button = browser.find_elements_by_name(
        'commit')[0]
    email_field.send_keys(USER_NAME)
    pwd_field.send_keys(PASSWORD)
    login_button.click()
```

Such an approach, which relies on navigating the DOM tree and performing virtual clicks, etc., is suboptimal.  One obvious reason is that the DOM tree can (and does) change without notice, requiring the client to be modified each time.

Clearly the more desirable approach is to create a RESTful API such as already exists for accessing published SafeCast data.

A benefit of formally supporting and documenting a login / upload / submission API is that someone (like myself) could distribute client-side apps to the whole SafeCast community, enabling everyone to become more efficient in their uploading & submission.

I am therefore requesting the safecastapi developers to kindly consider adding HTTP(S) API calls to allow the following:

1. Login
2. Upload (and batch upload would also be nice, but low priority).   It should be possible to populate all the standard fields which are typically filled in by hand through a browser.
3. Submission

Many thanks!

Larry

**Comment by elafargue** [comment]
The Safecast API already is a RESTful API, what specific part are you missing?

As an example, you can take a look at the source code of the Safecast Android app, and you can see how it uses the REST API endoing to send bGeigie logs: https://github.com/Safecast/Drive-android/blob/master/wizkers/oem/nuclear/www/js/app/instruments/bgeigie/display_log.js Line 301 onwards. You can POST your log to the /bgeigie_imports.json endpoint. Check the code I just shared for the parameters you need to have in your POST.

There is no need for any scraping, at least the idea didn't occur to me when I implemented the app :)

Hope this helps!

**Comment by lbrichards** [comment]
Thanks for the explanation.  Unfortunately I don't have access to an Android device, but I can sort of make out how you're doing the upload.  What I cannot find is how to **submit** the uploaded data.  

Indeed, when I look at [this](https://api.safecast.org/) I find only a single entry on bGeigie import.  I find nothing on submission.  Moreover, clicking that entry does not take me to any documentation of how to use this API call.  

The aforementioned documentation tells me that each API call wants a json file.  All I have is the SD card from my bGeigie full of (presumably) binary files containing measurements.  Is there a single location where I can see what key-value pairs should go into this json file?

Maybe I did not state my problem very well.  What I have is a big pile of gGeigie files that I would like to upload and **submit** in an automated fashion.  I see there is a restful API for other tasks, so what I guess I'm only asking for the addition of one -- possibly two -- more tasks.

**Comment by lbrichards** [comment]
I see now that each new measurement file is supposed to go through these six stages:

1. Uploaded
2. Processed
3. Meta-data added
4. Submitted
5. Approved
6. Live

As a data collector / uploader, I obviously only need to automate steps 1-4.

I also need to handle exceptions for each transaction type.  Is there somewhere documentation of the error cases?  For example, sometimes I receive a reply containing "already exists," which is self-explanatory.  But I would suspect there must be others that I haven't yet encountered.

**Comment by lbrichards** [comment]
### a word about ["Using the API"](https://api.safecast.org/en-US/home) 

I notice that all the examples shown here, with one exception, are GETs.  The only POST example is adding a new device.  Now, I cannot imagine why an ordinary bGeigie user like myself would wish to automate the addition of a new device using an API, since this is a very rare event.  This all confirms my impression that the SafeCast API was designed primarily to provide access to published SafeCast data, e.g. to researchers and the like.  It seems to suggest that providing bGeigie data collectors with the ability to automate the data submission process has not -- so far, at least -- been a priority objective.  But hey, there's nothing wrong with that.  Nobody ever anticipates all future requirements at the start of a project.

**Comment by elafargue** [comment]
Even without access to an Android device, I encourage you to visit the source code link I shared above: https://github.com/Safecast/Drive-android/blob/master/wizkers/oem/nuclear/www/js/app/instruments/bgeigie/display_log.js

If you look at the repository for the Safecast:Drive app, you will notice that this app can be compiled for Android, IOS as well as on Mac and Windows computers - or even run a Raspberry Pi as a server - , do you do not need an Android device to test.

From line 301 onwards, you will see how to do exactly what you are describing:

POST to api.safecast.org/bgeigie_imports.json
Parameters:
```
'api_key': Your API key
bgeigie_import[name]': The name for your import
bgeigie_import[credits]': The name for the uploader
'bgeigie_import[cities]': The city/location related to the upload
'bgeigie_import[description]': The description
```
Pretty straightforward :) I am planning to include the rest of the parameters in the next release of the app to go all the way to subscription. You are right, there is no formal documentation besides the source code of the api itself, which can be a bit daunting...

**Comment by lbrichards** [comment]
Thanks.  I did take a look at your javascript and I understand how it is uploading now.  Well commented.  Thank you for accepting to take on the additions to the API to support actions up through "subscribe."  I look forward to automating everything when the new features become available.

**Comment by lbrichards** [comment]
BTW, is this the correct place to request an update to the API documentation?  Or in a separate repo?

**Comment by lbrichards** [comment]
BTW, I see an api_key in your javascript app, but no password.  Does this mean that anyone with the api_key can submit data to that account without performing authentication?

**Comment by elafargue** [comment]
Yes, this is a very standard way of doing simple API authentication - if you are a registered user, you can request an API key on api.safecast.org and use that API key to authenticate your requests. It is up to you as a user to ensure you protect this API key. Every user has a different API key, of course.

In Safecast:Drive, the first thing the app asks you is your api.safecast.org username/password, so that the app can retrieve and store the API key in its settings and use it for later submissions.

**Comment by lbrichards** [comment]
If the potential damage of a stolen API key is low (optimism), and we trust that all API key holders are going to behave responsibly (more optimism), then sending the API key over an unencrypted connection in cleartext is sensible.

**Comment by thinrope** [comment]
Well, here is what might happen:
* impersonate someone
 i.e. "give her/him credit" for your work (if legitimate) , or try to discredit her/him by submitting wrong data
* DoS the server
 (but there are easier ways to do it)
* some other (public secret within Safecast dev ring) issues

So far all have been addressed/prevented with the manual review process (step [4]->[5] above).
And please use the HTTPS endpoint by all means https://api.safecast.org/ (the legacy HTTP is kept for underpowered uC devices that cannot handle HTTPS)

**Comment by elafargue** [comment]
I second Kalin's comment: please never use http to connect to the API, only use https.

**Comment by lbrichards** [comment]
That's great news that HTTPS can be used for POST as well.  We should definitely update the API docs to let the world know.  I assumed that the HTTP approach in this app was the recommended way:
https://github.com/Safecast/Drive-android/blob/master/wizkers/oem/nuclear/www/js/app/instruments/bgeigie/display_log.js#L351  
(HTTP, port 80)

**Comment by matschaffer** [comment]
https://github.com/Safecast/safecastapi/issues/440 is pretty related here.

I think @eitoball and I are both of the opinion that a swagger definition will be of more use than the in-view API examples (originally implemented 5 years ago, can you believe it!).

We should probably just pull those examples out once the swagger definition is more complete.

**Comment by matschaffer** [comment]
Going to close this in favor of https://github.com/Safecast/safecastapi/issues/478 specifically targeted at replacement of the in-browser API description page with a link something generated from our swagger API definition.

This should help keep API in sync with reality a bit more cleanly and also provide nice things like auto-generated client libraries.

**Comment by matschaffer** [comment]
Did a basic python example this evening, so posting it here incase we need to come back to it https://gist.github.com/matschaffer/2b073e3556fc47d9c30fe4c40368ac4e
