### ISSUE TITLE
Did the Aproval stop? lots of Datapackets hang since Months ?

### ISSUE THREAD

**Issue by Lugulbanda** [Safecast/safecastapi#455]
just a question, i was thinking the prozess had to be automated, but i noticed that some uploads are old, and some are very old....

**Comment by seanbonner** [comment]
Approvals are done by hand and the queue times vary for many reasons.

**Comment by Lugulbanda** [comment]
Hello Sean,

yes i know, and i know a few reasons why,  but that is very bad for planing the next tour, if u cant see were u had allready driven to, on the phone u can add the measurement to the tile map, but on the api webpage, i miss the same funktion for subbmitted Drives allready done and not aproved with the last version of the map, just to plan the next move.
i know its done by hand, thats why i asked if u need help in the past to speed that up, if i recall correctly if the data is only there and not transfered, its money to loose cuz its storred and not used....

but thx again for response Sean, btw on jannuar, i found the error in the GPS Signal loose, when working with IOS Drive App, but got no responce for that since then..... and the elevated 15 first measure slight elevation point, while the nano ist warming up problem, ist still poisoning the trustworthy database...

best wishes

Frank

 

PS: saw u were in Berlin, to sad i didnt read anything about that visit, or was someone in germay using ur name for upload?

 

Gesendet: Sonntag, 13. Mai 2018 um 11:05 Uhr
Von: "Sean Bonner" <notifications@github.com>
An: Safecast/safecastapi <safecastapi@noreply.github.com>
Cc: Lugulbanda <Starlord@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [Safecast/safecastapi] Did the Aproval stop? lots of Datapackets hang since Months ? (#455)


Approvals are done by hand and the queue times vary for many reasons.

**Comment by matschaffer** [comment]
@Lugulbanda does something like http://safecast.org/tilemap/?logids=27138,27139 help?

You should be able to specify a whole bunch of log IDs and get a live rendered map regardless of approval status.

**Comment by Lugulbanda** [comment]
ohhhh...... i didnt know u could do that  

http://safecast.org/tilemap/?y=50.508&x=8.58&z=10&l=1&m=0&logids=35113,35741,35712,35743,35658,35002,35079,35773,35828

thx Mat 

that helps alot for planing the next step  :))))

 

best wishes

Frank




 

Gesendet: Dienstag, 15. Mai 2018 um 03:46 Uhr
Von: "Mat Schaffer" <notifications@github.com>
An: Safecast/safecastapi <safecastapi@noreply.github.com>
Cc: Lugulbanda <Starlord@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [Safecast/safecastapi] Did the Aproval stop? lots of Datapackets hang since Months ? (#455)


@Lugulbanda does something like http://safecast.org/tilemap/?logids=27138,27139 help?

You should be able to specify a whole bunch of log IDs and get a live rendered map regardless of approval status.

**Comment by Lugulbanda** [comment]
hi guys, i know this is rather old, and i know there are many reasons, 
but i have a idea maybe worth to give it a few thoughts...

can we implement a funktion to the API wich generates a logids= xx,xx,xx, link wich includes all 
not approved measurements, 

i tryed to do it with the link from mat, but if u have 66 entrys to work down its always a bit of work, 
yes i can save it on one pc, or store it into a text file, but i work on many computers, lapptops plus i work on my smartphone.. sometimes readings get rejected sometimes approved, so its allso work keeping the link up to date everytime i change my PC or Phone..

why i want it from the approval list, cuz it may force people to fill out the Data for the Run, to see it with a simple click togehter on the full map with all the others not approved runs.. 

that makes working and planing on routs alot easyer 

just a mention what u think ?
