### ISSUE TITLE
Unable to consume API after Swagger integration

### ISSUE THREAD

**Issue by sarveswaran-m** [Safecast/safecastapi#464]
This is related to #440 
Am importing the URI [https://api.safecast.org/api_docs.json](https://api.safecast.org/api_docs.json) in [https://editor.swagger.io/](https://editor.swagger.io/) to generate a client. When I try to test the API from the page, it does not work.
Request : 

> curl -X GET "http://api.safecast.org/api_docs/users" -H  "accept: application/json"

Response:

> {"status":"404","error":"Not Found"}

The following works:
Request:
> curl -X GET "http://api.safecast.org/users" -H  "accept: application/json"

Response:

> [{"id":1189,"name":"Daniel Kottke","measurements_count":0},{"id":656,"name":"Minea Herwitz","measurements_count":75113},{"id":534,"name":"Stephanie","measurements_count":0},{"id":1117,"name":"Dim","measurements_count":0},{"id":1448,"name":"Miyoung, Kim ","measurements_count":0},{"id":572,"name":"Ranga Yogeshwar","measurements_count":77218},{"id":457,"name":"Dave Marks","measurements_count":2},{"id":1154,"name":"hirakawa koki","measurements_count":0},{"id":1050,"name":"FredoDavid","measurements_count":0},{"id":937,"name":"Meguro-safe","measurements_count":0},{"id":1063,"name":"Dominick Romano","measurements_count":15670},{"id":106,"name":"nudnik","measurements_count":798},{"id":458,"name":"JVonD","measurements_count":4},{"id":1082,"name":"Bert","measurements_count":0},{"id":1120,"name":"Gaku Oikawa","measurements_count":34568},{"id":88,"name":"the_STIG","measurements_count":30839},{"id":916,"name":"mariPi","measurements_count":0},{"id":322,"name":"fraserxv","measurements_count":0},{"id":344,"name":"Quarta-Rad","measurements_count":0},{"id":329,"name":"Maxim","measurements_count":0},{"id":1477,"name":"DanilMzl","measurements_count":0},{"id":848,"name":"Artipstito","measurements_count":0},{"id":326,"name":"jon hendricks jr","measurements_count":0},{"id":333,"name":"Michael Gakuran","measurements_count":21867},{"id":338,"name":"Radu Soltan","measurements_count":0}]

The issue seems to be with the base_path defined in [this commit](https://github.com/Safecast/safecastapi/pull/449/commits/bcdc92f348c3c9f764b92f6c795d45768432960b). base_path is defined as '/api_docs'. I think, it should just be /

Ideally, I would have liked to re-open #440 to report this.
Since I do not have the permission to re-open a closed issue, I am raising a new issue.

I tested generating the client when the swagger implementation went in.
But I overlooked checking the exact response.
That is a miss from me :(

**Comment by sarveswaran-m** [comment]
Just changing base_path to / would not work, I suppose.
I tried testing with the generated Java client.
Used api.safecast.org/ as base path instead of api.safecast.org/api_docs.
api.safecast.org yields test/HTML and not the List of Users as expected.
Please refer to the attachment for details.
![selection_080](https://user-images.githubusercontent.com/34768285/41094319-846abc4e-6a6b-11e8-8cce-7d2bc11f1a40.png)

**Comment by eitoball** [comment]
@sarveswaran-m 

You need to provide minimum code to reproduce your error and how to reproduce. 

Anyway, I guess that you use [swagger-codegen](https://github.com/swagger-api/swagger-codegen) to produce code. And your test code is like:

```java
@Test
public void usersGetTest() {
  io.swagger.client.DefaultApi api = new  io.swagger.client.DefaultApi();
  java.util.List<io.swagger.model.User> users = api.usersGet();
}
```

Yeah, maybe `base_path` setting is wrong, but there is a way to reconfigure your side. You could use your own client instead like:

```java
@Test
public void usersGetTest() {
  io.swagger.client.ApiClient client = new io.swagger.client.ApiClient();
  client.setBasePath("https://api.safecast.org");
  client.setDefaultHeader("Accept", "application/json");
  // client.setDebugging(true);
  io.swagger.client.DefaultApi api = new  io.swagger.client.DefaultApi(client);
  java.util.List<io.swagger.model.User> users = api.usersGet();
}
```

**Comment by sarveswaran-m** [comment]
@eitoball 

I generated a Java client using 'Generate Client' option @ [https://editor.swagger.io/](https://editor.swagger.io/).
The base-path is already set to /
```

public class ApiClient {

    //private String basePath = "https://api.safecast.org/api_docs";
    private String basePath = "https://api.safecast.org/";
    private boolean debugging = false;
    private Map<String, String> defaultHeaderMap = new HashMap<String, String>();
```
The test method looks as given below:

 ```
@Test
    public void usersGetTest() throws ApiException {
        List<User> response = api.usersGet();
        assert( (response != null) & (response.size() >0));
        // TODO: test validations
    }
```

Exception stack trace:

> Content type "text/html; charset=utf-8" is not supported for type: java.util.List<io.swagger.client.model.User>
> io.swagger.client.ApiException
> 	at io.swagger.client.ApiClient.deserialize(ApiClient.java:720)
> 	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:915)
> 	at io.swagger.client.ApiClient.execute(ApiClient.java:842)
> 	at io.swagger.client.api.DefaultApi.usersGetWithHttpInfo(DefaultApi.java:494)
> 	at io.swagger.client.api.DefaultApi.usersGet(DefaultApi.java:481)
> 	at io.swagger.client.api.DefaultApiTest.usersGetTest(DefaultApiTest.java:89)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.apache.maven.surefire.junitcore.ClassDemarcatingRunner.run(ClassDemarcatingRunner.java:58)
> 	at org.junit.runners.Suite.runChild(Suite.java:128)
> 	at org.junit.runners.Suite.runChild(Suite.java:27)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
> 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:62)
> 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:139)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
> 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
> 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
> 

I am not setting the client accept header explicitly.
Not sure whether that is the reason for the issue.
Let me try that and get back.

**Comment by eitoball** [comment]
@sarveswaran-m 

I was able to reproduce your error. Thank you for the details.

And, editor.swagger.io seems to be using swagger-codegen to generate code. So, the solution is basically same; creating `ApiClient` instance and setting it to `DefaultApi`. It seems that you need to set `Accept` header to get JSON-format content.

```java
 @Test
    public void usersGetTest() throws ApiException {
        ApiClient client = new ApiClient();
        client.setBasePath("https://api.safecast.org");
        client.addDefaultHeader("Accept", "application/json");
        client.setDebugging(true);
        DefaultApi api = new DefaultApi(client);
        List<User> response = api.usersGet();

        // TODO: test validations
    }
```

**Comment by matschaffer** [comment]
Looks like we've got consumes/produces on https://api.safecast.org/api_docs.json now. Thanks for the quick fix @eitoball !

**Comment by sarveswaran-m** [comment]
Checked again after setting accept header.
Works fine now. Thanks!

![selection_081](https://user-images.githubusercontent.com/34768285/41202342-79c6f2cc-6ce5-11e8-82aa-c737af2612e4.png)
