### ISSUE TITLE
Targeted, daily CSV export of bgeigie data

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#470]
Jeffrey Imbrogno's work has been focused on data sets for particular cities:  Uppsala, Hong Kong, Seoul, Taipei, Amsterdam, Perth, Sydney, Honolulu, and Munich

Depending on the size of the data set, sometimes the API will time out (~60k points).

I think the simplest short-term workaround will be so produce daily CSV exports for each of these cities. A 3km circle from city center should be sufficient.

Some example queries:
- Hong Kong - https://api.safecast.org/measurements.csv?distance=3000&latitude=22.316905+&longitude=114.157841
- Uppsala - https://api.safecast.org/measurements.csv?distance=3000&latitude=59.8586+&longitude=17.6389

**Comment by Lugulbanda** [comment]
why is there such a focus on citys like munich ?

**Comment by kbfastcat** [comment]
underground zombies...
