### ISSUE TITLE
AWS Open Data Registration

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#512]
- [x] [registry yaml](https://github.com/awslabs/open-data-registry/blob/master/README.md) - https://github.com/awslabs/open-data-registry/pull/180
- [x] data structure readme ([example](https://docs.opendata.aws/landsat-pds/readme.html))
- [x] tutorial proposal including S3, Athena, RDS, possibly SNS ([example](https://medium.com/@openaq/get-faster-access-to-real-time-air-quality-data-from-around-the-world-c6f9793d5242)) - put ideas in https://github.com/Safecast/safecastapi/issues/512#issuecomment-446467640, can draft something more formal if AWS requires it
- [x] [terms acceptance](http://pages.awscloud.com/public-data-sets-applicants.html) (@seanbonner)

**Comment by matschaffer** [comment]
Updated https://github.com/Safecast/safecastapi/wiki/Data-Sets with field information to cover the data structure readme requirement

**Comment by matschaffer** [comment]
Tutorials:
- How to read the exported data from S3
- How to subscribe to our SNS topic
- How to query the data from athena (may require some reformatting of the data that's on s3 today)

**Comment by seanbonner** [comment]
Terms accepted!
