### ISSUE TITLE
Drive auto-approval

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#527]
There are some cases where we might want to automate some approval analysis:

- drive contains no measurements where CPM=0
- drive contains no measurements where CPM>90 (around 0.3uSv)
- no excessive invalid GPS (e.g. less than 10% of drive total)
- submission is from a bGeigie ID for which we have approved 10 drives in the past
- no rejected drives for that bGeigie ID in the past year

For starters we'll want to run this query and see what matches.

Once we have some confidence we'll likely want to make this a scheduled automatic job.

This is especially desirable in the case where we can rollback approval.

One possible refinement is to exclude the area around Daiichi in a circle of 80km.

We should prefer to look at the bGeigie ID over the user ID is that we have quite a few accounts used where volunteers use multiple bGeigies, so we keep an eye on new devices before auto approving.

**Comment by matschaffer** [comment]
Noting that we can't do `no excessive invalid GPS (e.g. less than 10% of drive total)` until the linked issue regarding invalid GPS is addressed.

Afaict, we discard the GPS validity info during drive file import.

**Comment by nokton** [comment]
Hmmm - you’re saying that the valid flags for CPM and GPS are not stored after import to the API? I thought these are stored. 

Best,
Pieter

**Comment by shoghicp** [comment]
I'm interesting on contributing. I can take a look into the stack and see what you have, will try to get a dev environment up and running.

**Comment by matschaffer** [comment]
Welcome @shoghicp ! We'd certainly appreciate the help. The wiki has info on setting up local environments and we can send you a slack invite if you need any real time help.

**Comment by shoghicp** [comment]
If you have Slack, that would be great. Will have time over weekends to look at this, if you want to send an invite it's (same as username) at gmail.com

**Comment by matschaffer** [comment]
@shoghicp 	we had a new helper join (@ZacharyCChang0828 	) so figure he'll take point to try to move this issue forward. Of course feel free to help out where you can.

**Comment by matschaffer** [comment]
Noting this test result from @ZacharyCChang0828 

```
safecast_development=# select A1.bgeigie_import_id, count(A1.gps_fix_indicator) as invalid_gps_count,A2.lines_count,count(A1.gps_fix_indicator)*1.0/lines_count*1.0 percentage from bgeigie_logs A1,measurement_imports A2 where A1.bgeigie_import_id = A2.id and A1.gps_fix_indicator = 'V'  group by A1.bgeigie_import_id , A2.lines_count having count(A1.gps_fix_indicator)*1.0/lines_count*1.0 > 0.1;
 bgeigie_import_id | invalid_gps_count | lines_count |       percentage
-------------------+-------------------+-------------+-------------------------
                 3 |              2008 |        4979 | 0.403293834103233581040
                 4 |               947 |        2311 | 0.409779316313284292510
```

**Comment by ZacharyCChang0828** [comment]
This will query drives with rejected drives from the same bgeigie_id in the past year

`select distinct a4.id from (select distinct a1.device_serial_id from bgeigie_logs a1, measurement_imports a2 WHERE a1.bgeigie_import_id = a2.id and a2.created_at > localtimestamp - interval '1 year' and a2.rejected = 't') a3,measurement_imports a4,bgeigie_logs a5 where a3.device_serial_id = a5.device_serial_id and a4.id = a5.bgeigie_import_id;`

**Comment by ZacharyCChang0828** [comment]
The following should query drive from a bgeigie id that we have approved 10  drives in the past

```
select id, device_serial_id,count from (select a1.id, a1.device_serial_id,a2.count from (select distinct a1.device_serial_id, a2.id from bgeigie_logs a1 inner join measurement_imports a2 on a2.id = a1.bgeigie_import_id) a1 inner join (select a1.device_serial_id,count(distinct bgeigie_import_id) from bgeigie_logs a1,measurement_imports a2 where a1.bgeigie_import_id = a2.id and a2.approved = 't' group by a1.device_serial_id) a2 on a1.device_serial_id = a2.device_serial_id) a1 where count > 9;
```

**Comment by matschaffer** [comment]
Nice formatting update! Can’t wait to try it on prod!

**Comment by ZacharyCChang0828** [comment]
The following query select drives that contains measurement where cpm = 0 or cpm > 90

```
SELECT distinct measurement_import_id 
   FROM measurements 
WHERE value = 0 
        OR value >90;
```

**Comment by eitoball** [comment]
I have a couple of thoughts on this.

1) Instead of having columns in `bgeigie_imports` table, how about having separate table and call it like `bgegie_import_statistics`. This table would have `statistic` column with JSON type and usual columns like `id`, `created_at`, and `updated_at`.  I think that we might change criteria for automatic approvals, so JSON column is much flexible. In this `statistic` column, we could have statistic about bGeigie import like number of zero CPMs, highest CPM, lowest CPM, etc.
2) I think that we should process asynchronously. More criteria we have, slower this process would be, and whole import processes would be slower. Therefore, we should process this asynchronously with delayed_job.
3) I already said in (1). Instead of saving query like "Does this import have '0' CPM?", we should collect statistics of imports like "number of '0' CPMs" and "lowest CPM", etc. Then, query on collected stats.

**Comment by matschaffer** [comment]
the rules in the description have been built & deployed to prod.

Since only moderators can see/use it right now here are some screenshots of the basic idea that we'll expand over time.

<img width="1002" alt="Bgeigie_Import__40451____bGeigie_Imports____Safecast_API" src="https://user-images.githubusercontent.com/690/69851765-d931d380-12c5-11ea-9eca-7f3fe081cc8e.png">

<img width="982" alt="Bgeigie_Import__18119____bGeigie_Imports____Safecast_API" src="https://user-images.githubusercontent.com/690/69851768-db942d80-12c5-11ea-841a-1bac998fde03.png">

**Comment by nokton** [comment]
Hurray!
