### ISSUE TITLE
Try out Falcon server

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#548]
I ran into @ioquatix (:wave:) at RubyKagi who mentioned https://github.com/socketry/falcon should be a drop in rack/rails server.

Could be interesting to try for either api or ingest so making a note here.

**Comment by ioquatix** [comment]
What help do you need?

**Comment by matschaffer** [comment]
Do you know offhand if anyone has it running on AWS beanstalk?

Both apps run there today on the Ruby+Puma stack (latest ARN can be checked on https://github.com/Safecast/safecastapi/blob/master/lib/elasticbeanstalk_helper.rb#L18-L25).

Guessing falcon would replace Puma here so if you know of anyone with a working rails+falcon on beanstalk setup that'd be a big help.

**Comment by matschaffer** [comment]
Fwiw I'd really love to get to a docker stack, but I haven't had luck getting rails to _not_ write to the docker file system once inside a container. So double bonus if you can point me toward someone with a falcon+rails on docker.

**Comment by ioquatix** [comment]
I've only done it on Heroku using a `Procfile`.

**Comment by matschaffer** [comment]
Ah well :) if you come across it let me know, otherwise we'll have to bang it out ourselves which always takes longer.

Seeing the procfile example couldn't hurt if you have it handy.

**Comment by matschaffer** [comment]
Ah, also the "help-wanted" is our label for issues that people can start on w/o knowing too much about the safecast biz domain.

**Comment by ioquatix** [comment]
https://github.com/socketry/utopia-falcon-heroku

**Comment by robouden** [comment]
Seems nice to move to falcon after reading about it at
https://github.com/socketry/falcon

regards
rob



Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> linkedin:robouden
<https://www.linkedin.com/in/roboudendijk>

**Comment by matschaffer** [comment]
See discussion on https://github.com/Safecast/safecastapi/issues/548

**Comment by ioquatix** [comment]
Nice, care to give a summary? How did it work out?

**Comment by auspicacious** [comment]
I think Mat meant https://github.com/Safecast/safecastapi/pull/673

**Comment by matschaffer** [comment]
Totally did. Thanks @auspicacious !
