### ISSUE TITLE
Safecast IOS does not require for microphone permission

### ISSUE THREAD

**Issue by yangjiel** [Safecast/safecastapi#567]
I know that it maybe improper to post here but I couldn't find a place to report the issue for the IOS app "Safecast" which can connect the iPhone with a geiger count or spectrometer.

I have the problem that the app does not require the microphone permission and I cannot use the app in any ways. Apple now requires developers to add a text to the main plist file stating why the app wants microphone permissions starting from IOS 12. If it is not there people simply don't get the question and cant enable it.

However, you might not found this issue because apple allows you to migrate your app settings from older IOS version to newer IOS version.

Steps to reproduce the issue:
1, An Apple IOS device that is IOS 12 or newer operating system;
2, Apply for a new Apple ID;
3, Change your apple ID to the new one on the IOS device (also for the itunes and apple store)
4, Download the Safecast
5, There is no Safecast under the settings -> Privacy -> Microphone.

Such the app cannot perform any use.

**Comment by Frangible** [comment]
Thanks for the report.  This is a known issue, and indeed is due to the reasons you say.  It's been resolved in the development version of the app but I don't have an ETA on its release right now.  Due to the fix and this being a different project I'll be closing this out for now.  Thanks!
