### ISSUE TITLE
Set up elb/job overview dashboard for ingest

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#570]
We have https://grafana.safecast.cc/d/W7c552kZz/api-overview?orgId=1 for API, the same would be good for ingest.

It should also make it easier to spot if we end up rejecting any data once #540 is done and we're requiring `device_urn` to be set.

**Comment by auspicacious** [comment]
I copied the API dashboard and rewrote it to point to the metrics for the ingest systems:

https://grafana.safecast.cc/d/MoVFmrdZz/ingest-overview

There were a couple of places where instance ID was being used, for the worker hosts, and I replaced this with ELB group ID.

**Comment by matschaffer** [comment]
Looks awesome. I'd call this done
