### ISSUE TITLE
Upgrade ingest app servers to Ruby 2.6.5

### ISSUE THREAD

**Issue by auspicacious** [Safecast/safecastapi#577]
Upgrade ingest app servers (using Terraform etc.) to the latest stable version of Ruby (as of writing, 2.6.4), and document the process to make it easier in the future. This will make it easier for developers to work on the project -- the old version of Ruby it's currently using is not easy to build on the latest Fedora, Ubuntu, etc. releases as it depends on some older versions of libraries like OpenSSL that are no longer available in those distributions. (Of course, it may also be easier to address security issues when staying up-to-date).

Also note that currently the app and worker servers, via ElasticBeanstalk, appear to end up in random AZs. For best performance and cost, they should be in the same AZ as the database.

**Comment by eitoball** [comment]
2.6.5 is just released, so I updated card title
