### ISSUE TITLE
DEV synced users and API keys with production.

### ISSUE THREAD

**Issue by robouden** [Safecast/safecastapi#591]
To have a valid dev server we need to import/sync the users and API key on the dev server with the production server. Otherwise sending data is not possible.

**Comment by matschaffer** [comment]
to clear up this is for bgeigie-cast since the device has a prod/dev switch but only one API key.

For this we'd need a continuous sync.

Might not make as much sense to do this vs somethign like the dev_test flag that we have for solarcast testing.

**Comment by matschaffer** [comment]
#606 should make this unnecesary
