### ISSUE TITLE
Important: Need dynamic "measurement count" total for wordpress site

### ISSUE THREAD

**Issue by seanbonner** [Safecast/safecastapi#593]
Old version:
https://github.com/Safecast/measurement_count

A lot missing from that, need something that is more comprehensive and accurate for the new website.

**Comment by seanbonner** [comment]
Correct number is displayed here I think
https://api.safecast.org/en-US/measurements

**Comment by matschaffer** [comment]
Where does this count get used @seanbonner ?

**Comment by seanbonner** [comment]
Sorry, we solved this another way and I forgot about this issue. All set.
