### ISSUE TITLE
Static Sensor (nGeigies) data into Safecast DB

### ISSUE THREAD

**Issue by seanbonner** [Safecast/safecastapi#6]
As the data is sortable by sensor and device, there should be no more reason to keep the static sensor data out of the Safecast DB and in patchube/cosm instead. Would be good to get this data into our set - right now we don't display this on our own map or include it in our own datasets which is kind of annoying, so would be good to correct that.

**Comment by matschaffer** [comment]
@robouden do we have any nGeigies reporting anymore?

**Comment by robouden** [comment]
Yes, most devices with device_id from 0-999 should be considered nGeigie.

**Comment by matschaffer** [comment]
I see numbers in that range on https://grafana.safecast.cc/d/BwwekZ_mz/devices?orgId=1

So I think we're good to close here, but re-open if I've missed something.
