### ISSUE TITLE
Format nginx logs to include original client IP

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#623]
Should be able to use what's in https://aws.amazon.com/premiumsupport/knowledge-center/elb-capture-client-ip-addresses/

Might also be interesting to format as json (https://medium.com/bolt-labs/using-json-for-nginx-log-format-793743064fc4) for easier traversal with `jq` or ingest into elasticsearch.

Filing for both projects since the final config will be the same.

**Comment by auspicacious** [comment]
@matschaffer it looks like x-forwarded-for is already being logged? I've used it to troubleshoot within the past few months. Is this issue still valid? Thanks.

**Comment by matschaffer** [comment]
I may have just been confused. Thanks for checking in!
