### ISSUE TITLE
Drives not getting processed after upload

### ISSUE THREAD

**Issue by Lugulbanda** [Safecast/safecastapi#624]
hi, i have some issues with my newst drives on the api page... https://api.safecast.org/en-US/dashboard

i schould see : 45888,45887,45879,45878,45868,**45858,45857**,**45353**

but i only see:

processed:
45857, 45858

submitted not approved 
45353

the missing ones are all on the drive iosapp, marked as send

**Comment by seanbonner** [comment]
This sounds like a problem with your app not the API.

**Comment by matschaffer** [comment]
That dashboard link doesn't show drives so not sure what you're looking at.

Just spot checked a few of those IDs, and they all show up at this link https://api.safecast.org/en-US/bgeigie_imports?by_status=&by_user_id=&by_user_name=Lugulbanda&commit=Filter&order=id+desc&q=&rejected_by=&status=all&uploaded_after=&uploaded_before=&utf8=%E2%9C%93

**Comment by matschaffer** [comment]
Ah... I think we may have stopped processing again.

One of the ones you list is just new but processing hasn't kicked in https://api.safecast.org/en-US/bgeigie_imports/45888

**Comment by Lugulbanda** [comment]
they ara all new fresh from this year, only one was from last year..

the map of the measurement shows my drive but i dont see any measurments...

 
 

Gesendet: Donnerstag, 16. Januar 2020 um 16:09 Uhr
Von: "Mat Schaffer" <notifications@github.com>
An: Safecast/safecastapi <safecastapi@noreply.github.com>
Cc: Lugulbanda <Starlord@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [Safecast/safecastapi] missing uploads from drive app (#624)


Ah... I think we may have stopped processing again.

One of the ones you list is just new but processing hasn't kicked in https://api.safecast.org/en-US/bgeigie_imports/45888

**Comment by matschaffer** [comment]
Looks like the disk on the worker filled up. Got a new one and drives are re-processing. The instance wasn't responsive enough to tell me what was filling disk so will have to stay vigilant for the next time.

**Comment by matschaffer** [comment]
back at 0 unprocessed: https://api.safecast.org/en-US/bgeigie_imports?by_status=unprocessed&order=created_at+asc

I suspect your drives should be all visible as usual now @Lugulbanda 

Thanks for the heads up!

**Comment by Lugulbanda** [comment]
actualy i missing the hole api server side it started with login problems , login took very long to now not even loading , up to that apis with logids= are not loadet to the citrent map

Gesendet mit der GMX Mail App

Am 16.01.20 um 16:09 schrieb Mat Schaffer

**Comment by matschaffer** [comment]
Thanks! From looking at
https://grafana.safecast.cc/d/W7c552kZz/api-overview?orgId=1&refresh=5m&from=now-6h&to=now,
the DB is a bit backed up. I'll clear out in-flight queries which should
get api working.

You might also see tilemap issues (logids=) since we switched to a new
hosting provider but we expect those to clear up in the next ~6 hours.

-Mat

matschaffer.com

**Comment by Lugulbanda** [comment]
API Page Down got Bad Gateway as Answer from Server ?

 

 

Gesendet: Donnerstag, 16. Januar 2020 um 04:39 Uhr
Von: "Sean Bonner" <notifications@github.com>
An: Safecast/safecastapi <safecastapi@noreply.github.com>
Cc: Lugulbanda <Starlord@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [Safecast/safecastapi] missing uploads from drive app (#624)

This sounds like a problem with your app not the API.

**Comment by auspicacious** [comment]
Thank you for reporting this. We're looking at why API went down, but it should be back up right now.

This was not related to your original issue. In the future, please open a new issue for a new problem.
