### ISSUE TITLE
Add realtime-devices.json API call

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#628]
We've been having a lot of API stability problems lately. As a test I disabled the update.php job for realtime.safecast.org (https://safecast.slack.com/archives/C026F2Q1U/p1579991444036500)

![Pasted_Image_1_27_20__2_42_PM.png](https://images.zenhubusercontent.com/579ea40fe40e5714b16cbfe1/bc4bbe0e-5770-41cd-ae30-30ab5e9a2e2d)

Since then the database has been much healthier and has had a 100% burst I/O balance for most of the time.

My read on this is that as our data size increased and probably as we added even a small handful of devices, realtime’s update.php got to the point where it was continually asking for new data points and even overlapping itself (so many update.php jobs were running at the same time).

The burden here is a double whammy too since we rely on burst balance to get good DB performance w/o having to spend too much money on provisioned iops (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html).

I’m 90% certain we can provide the same data update.php is requesting with a single query & API call that will probably take less than a minute to execute. Perhaps even order of seconds.

**Comment by matschaffer** [comment]
I've confirmed that the update* scripts on the server match what's in git, so we can use https://github.com/Safecast/Realtime-Website/blob/master/cli/update.php as a reference & edit point for the realtime updates once we have an API to serve it.

**Comment by matschaffer** [comment]
The specific loop is https://github.com/Safecast/Realtime-Website/blob/master/cli/updateSensorsMeasurements.php#L96-L115

**Comment by matschaffer** [comment]
Some sample logs from running the script:

```
> Querying the API with URI https://api.safecast.org/en-US/measurements.json?device_id=300022&unit=cpm&per_page=1&order=captured_at+desc
> Measurement found
> Querying the API with URI https://api.safecast.org/en-US/measurements.json?captured_after=&captured_before=&device_id=300022&unit=cpm&per_page=1&order=value+desc
> Measurement found
Retrieving measurements for device 300021
> Querying the API with URI https://api.safecast.org/en-US/measurements.json?device_id=300021&unit=cpm&per_page=1&order=captured_at+desc
> Measurement found
> Querying the API with URI https://api.safecast.org/en-US/measurements.json?captured_after=&captured_before=&device_id=300021&unit=cpm&per_page=1&order=value+desc
> Measurement found
Retrieving measurements for device 100292
> Querying the API with URI https://api.safecast.org/en-US/measurements.json?device_id=100292&unit=cpm&per_page=1&order=captured_at+desc
> Measurement found
> Querying the API with URI https://api.safecast.org/en-US/measurements.json?captured_after=&captured_before=&device_id=100292&unit=cpm&per_page=1&order=value+desc
> Measurement found
Retrieving measurements for device 100291
> Querying the API with URI https://api.safecast.org/en-US/measurements.json?device_id=100291&unit=cpm&per_page=1&order=captured_at+desc
> Measurement found
> Querying the API with URI https://api.safecast.org/en-US/measurements.json?captured_after=&captured_before=&device_id=100291&unit=cpm&per_page=1&order=value+desc
> Measurement found
Retrieving measurements for device 100362
> Querying the API with URI https://api.safecast.org/en-US/measurements.json?device_id=100362&unit=cpm&per_page=1&order=captured_at+desc
> Measurement found
> Querying the API with URI https://api.safecast.org/en-US/measurements.json?captured_after=&captured_before=&device_id=100362&unit=cpm&per_page=1&order=value+desc
> Measurement found
Retrieving measurements for device 100361
> Querying the API with URI https://api.safecast.org/en-US/measurements.json?device_id=100361&unit=cpm&per_page=1&order=captured_at+desc
> Measurement found
```

**Comment by matschaffer** [comment]
Not sure how to do both in one query, but easy enough in 2.

```
safecast=> select device_id, max(value) from measurements where device_id in (300022, 300021, 100291, 100292) group by device_id;
 device_id | max
-----------+-----
    300021 |  82
    100291 |  65
    300022 |  56
    100292 |  23
(4 rows)


safecast=> select distinct on (device_id) device_id, captured_at, value from measurements where device_id in (300022, 300021, 100291, 100292) order by device_id, captured_at desc;
 device_id |     captured_at     | value
-----------+---------------------+-------
    100291 | 2020-01-27 06:46:04 |    42
    100292 | 2020-01-27 06:46:04 |    12
    300021 | 2020-01-27 05:55:41 |    44
    300022 | 2020-01-27 05:55:41 |    42
(4 rows)
```

**Comment by robouden** [comment]
If you can give me a better query string that makes it easier for the API to respond we can make it from the update.php script.

**Comment by matschaffer** [comment]
There's nothing in the API right now. We'll have to make it.

**Comment by robouden** [comment]
How about what @Ray was sugesting:

"just keep a simple separate table or file (also easily cached in memory) that has nothing but the min/max/latest/device name/serial number/etc for all devices.  "

**Comment by matschaffer** [comment]
Exposing such a cache would still require a new endpoint.

Implementing the endpoint as I proposed (list of devices in, table of max/last out) would also avoid the loop & network overhead.

Once the endpoint exists we can implement it as simpler queries, or a cache access. I think either would be enough to avoid our current scaling issues.

**Comment by auspicacious** [comment]
Agreed, the thing about implementing such caches is that, much as with a event-based system, you have to be very careful about how your inputs are processed. They can dramatically increase the complexity of a system. Going down that road without some agreement on future architecture, e.g. statements that everyone agrees on, like, for example, "all cached data updates should occur via SQL triggers" (as an example! I might not agree!) can lead to increasingly unpredictable or inconsistent behavior given the multiple ways that data enters our systems. For now, let's simplify the query.

**Comment by matschaffer** [comment]
Looks like just the max took 80s for all devices queried from realtime ![Screen Shot 2020-01-30 at 9.45.29 PM.png](https://images.zenhubusercontent.com/579ea40fe40e5714b16cbfe1/cb713f51-5d4d-4095-81ee-23e33c9acd29)

**Comment by matschaffer** [comment]
and about 43s for latest ![Screen Shot 2020-01-30 at 9.56.08 PM.png](https://images.zenhubusercontent.com/579ea40fe40e5714b16cbfe1/9db1401f-94d5-424d-bd66-8d50c4d3b9de)

We may need that cache table afterall.

**Comment by robouden** [comment]
I did set up RT to query only the last measurement and disabled the max query. That would explain the nearly half time.

**Comment by robouden** [comment]
It would be great if we can get the JSON file out. Preferably in a similar format as TTserve. But the CPM, PPM in separate fields. 

Would it be possible to have a simple view setup for admin in wich we can modify the fields, add fields, delete fields, etc? That would be a replacement for the Google sheets now being used for TTserve to supply the additional information about the users/devices/data.

**Comment by matschaffer** [comment]
Closing in favor of #606
