### ISSUE TITLE
Switch ingest workers to run after new app is deployed

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#645]
I noticed in the last deploy that new code didn't get picked up

Looks like https://github.com/Safecast/ingest/blob/master/.ebextensions/workers.config#L41-L63 is wrong. These are `command`s so they're running before `/var/app/current` is updated to the new deployment.

I think `container_command` might also be too early. Need to figure out the right way to trigger a restart only after the app has been swapped into place.

**Comment by matschaffer** [comment]
Looks like the job restart should get moved to a post deploy hook https://junkheap.net/blog/2013/05/20/elastic-beanstalk-post-deployment-scripts/

**Comment by robouden** [comment]
Thanks for finding the issue.

**Comment by auspicacious** [comment]
Going to take this up + the same error in api as well. Should be quick to fix.
