### ISSUE TITLE
Upgrade API to Rails 6

### ISSUE THREAD

**Issue by auspicacious** [Safecast/safecastapi#647]

**Comment by sasharevzin** [comment]
A pretty big jump, maybe v5 first?

**Comment by sasharevzin** [comment]
Currently blocked by the ruby version. Rails 6 requires at least Ruby 2.5. I see @eitoball is working on it https://github.com/Safecast/safecastapi/pull/669

**Comment by eitoball** [comment]
https://github.com/Safecast/safecastapi/pull/798
