### ISSUE TITLE
Secure api secret_key_base

### ISSUE THREAD

**Issue by auspicacious** [Safecast/safecastapi#665]
The value in `config/initializers/secret_token.rb` in production should not be available in Git.

Moreover, we should look at updating to the `config/secrets.yml` configuration style. See https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#config-secrets-yml

**Comment by sasharevzin** [comment]
Let’s set env var first on prod and staging?

@auspicacious ^^^

**Comment by auspicacious** [comment]
@sasharevzin could you explain more?

**Comment by sasharevzin** [comment]
> @sasharevzin could you explain more?

Like we need to set the variable somewhere ENV["SECRET_KEY_BASE"]

**Comment by auspicacious** [comment]
Yes, we do need to set a variable in the config, but will the application see it automatically? Or do I need to modify the application?

**Comment by sasharevzin** [comment]
> Yes, we do need to set a variable in the config, but will the application see it automatically? Or do I need to modify the application?

As long as `$ echo $SECRET_KEY_BASE` is in bash console available OR app starts with `SECRET_KEY_BASE` like SECRET_KEY_BASE=blabla rails, then the app will see it

Basically, we should set this `ENV` the same way as we do for AWS: https://github.com/Safecast/safecastapi/blob/master/.env.sample#L2
