### ISSUE TITLE
Remove store_prefix from store_dir

### ISSUE THREAD

**Issue by sasharevzin** [Safecast/safecastapi#675]
Following the PR https://github.com/Safecast/safecastapi/pull/587/files#r338905415, I would like to propose removing `store_prefix` (https://github.com/Safecast/safecastapi/blob/master/app/uploaders/file_uploader.rb#L13) on `store_dir` to avoid adding more personal folders to https://github.com/Safecast/safecastapi/blob/master/.gitignore#L13-L15

I don't see any reasons why would we have `store_prefix`

**Comment by sasharevzin** [comment]
@matschaffer @auspicacious any objections?

**Comment by auspicacious** [comment]
@sasharevzin Thank you for following up on this, I have no objections. I would appreciate having this fixed.

**Comment by matschaffer** [comment]
no objections from me. Looks like I added it back in https://github.com/Safecast/safecastapi/pull/415 but in hindsight maybe not a great idea

**Comment by matschaffer** [comment]
Looks like this also causes upload fail on windows so let’s kill it.

**Comment by sasharevzin** [comment]
I’ll remove
