### ISSUE TITLE
Datakind exporting

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#704]
- [x] back fill device_urn and device_sn for older data in elasticsearch. Grafana and kibana both mainly use that. Plus this ensures postgres is an "untouched" copy of the data. (done - https://github.com/Safecast/ingest/pull/94)

- [x] make sure we have a view which works for DataKind purposes - done: http://kibana.safecast.cc/app/kibana#/discover/c22931c0-ae14-11ea-a80c-6dde8223854e

- [x] build some kind of script to export the above view into month CSVs - kibana has support for this, but more than one month at a time is too big, so will need to script to get 3 years. (https://github.com/Safecast/ingest/pull/95)

- [x] Deliver CSVs to publicly linkable google drive folder (https://drive.google.com/drive/folders/13tPy3ZxMDfLYYJkplxY6AH76TJ4zGOEz?usp=sharing)

**Comment by matschaffer** [comment]
Update: 

1. Made some headway on backfilling data. Looks like we'll first need an enrichment index which I was able to build with this

```
POST _watcher/watch/_execute
{
  "watch": {
    "trigger": {
      "schedule": {
        "interval": "10s"
      }
    },
    "input": {
      "search": {
        "request": {
          "indices": [
            "ingest-measurements-*"
          ],
          "body": {
            "size": 0,
            "aggs": {
              "devices": {
                "terms": {
                  "field": "device",
                  "size": 1000
                },
                "aggs": {
                  "device_urns": {
                    "significant_terms": {
                      "field": "device_urn"
                    }
                  },
                  "device_sns": {
                    "significant_terms": {
                      "field": "device_sn"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "actions": {
      "index_payload": {
        "index": {},
        "transform": {
          "script": """
            return [ "_doc": ctx.payload.aggregations.devices.buckets.stream()
              .map(b -> {
                def device = [
                  "_index": "device-details",
                  "_id": b.key,
                  "device": b.key
                ];
                if (b.device_urns.buckets.length > 0) {
                  device["device_urn"] = b.device_urns.buckets[0].key;
                }
                if (b.device_sns.buckets.length > 0) {
                  device["device_sn"] = b.device_sns.buckets[0].key;
                }
                device
              })
              .collect(Collectors.toList())
            ];
          """
        }
      }
    }
  }
}
```

2. got 👍  on the saved search from Saksham http://kibana.safecast.cc/app/kibana#/discover/c22931c0-ae14-11ea-a80c-6dde8223854e

3. No updates on a script yet


In parallel @robouden has been looking at how we could do this from `psql`

**Comment by matschaffer** [comment]
<img width="1792" alt="Screen Shot 2020-06-30 at 10 29 24 PM" src="https://user-images.githubusercontent.com/690/86131893-2eb2b500-bb21-11ea-9a4d-69d617f650e0.png">

I think I got the re-index working. The document in the screenshot `_id:AV5fglgAUq1IpVvkevzs` did not previously have device_sn and device_urn, but it does now.

**Comment by robouden** [comment]
I will check. I made an export table for him. on[ (https://grafana.safecast.cc/d/DFSxrOLWk/safecast-device-details?orgId=1&from=1502840567433&to=1593572246412&var-device_urn=safecast:743902494)
](url)

**Comment by matschaffer** [comment]
I made some headway on the monthly kibana exporter in https://github.com/Safecast/ingest/pull/95

Still need to write the part to make the queries, and download the CSVs as they become available.

**Comment by matschaffer** [comment]
Looks like we're all set here. Will re-open if saksham needs anything else
