### ISSUE TITLE
Support multiple metrics for grafana map rollover

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#732]
See https://grafana.safecast.cc/d/u5-KaDEWk/air-data?editPanel=4&orgId=1

<img width="1373" alt="Screen_Shot_2020-11-05_at_4_15_36" src="https://user-images.githubusercontent.com/690/98197091-310e9b00-1f69-11eb-970a-4a1551ec15c4.png">

**Comment by robouden** [comment]
Tried it but there are errors:
1) Roll over has now undefined as data (maybe correct but if undefined we should blank out the field).
2) How can we set labels for the unit on multiple metrics?
![Screenshot from 2020-12-24 18-43-40](https://user-images.githubusercontent.com/1387190/103080133-93565480-4618-11eb-9b90-94130f07d4a8.png)

**Comment by robouden** [comment]
One more point is can we set a limit to the decimals?

**Comment by matschaffer** [comment]
Once you add another field you need to update the "Metric field" to match the new field name. So probably "Average lnd_7318u" for that graph.

Then it'll move up to where you see the "undefined" in your screenshot.

**Comment by matschaffer** [comment]
I think https://github.com/panodata/grafana-map-panel/issues/39 is probably the best issue to address the number formatting. 

You _can_ have elasticsearch round for you, but you'd need scripted_metric for that which doesn't appear supported by grafana atm (https://github.com/grafana/grafana/issues/3441)
