### ISSUE TITLE
Make an airnote-friendly version of the bGeigie Log Viewer

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#749]
We use bGeigie Log Viewer on pages like https://api.safecast.org/en-US/bgeigie_imports/10758 to show the drive on a map.

We also link off to a version of the map that shows the drive in the context of surrounding data.

We'd like to do something similar for the airnote pages. https://api.safecast.org/en-US/device_stories/140 is an example, though we might make a new page soon.

Ideally we'd like to be able to show the device in the context of larger air devices.

**Comment by Frangible** [comment]
To be clear the current air data display on the tilemap is not by device but rather by time/location and any query results of device ID are computationally expensive for the DB server and should be considered a legacy feature at this time.

There is no data source for the tilemap to pull from to display individual sensors.  This is an entirely different paradigm than what is currently implemented.  While it would be possible to move in this direction I think this is probably a misunderstanding of what is currently being shown?  If not please elaborate with the use case for this.

**Comment by matschaffer** [comment]
I'm trying to capture a final point that @rayozzie brought that our airnote customer flow will probably look something like:

- receive device
- mount device
- scan code
- see data from my device
- zoom out to see my device contributing to the world <-- this one

Today we don't have any good way to show a given device alongs side the rest of the data.

I was hoping we could  do something like https://map.safecast.org/?logids=10758 where you can see the data coming from your own device in the context of the rest of our sensors.

The data is on https://grafana.safecast.cc/d/7wsttvxGk/airnote-device-details?orgId=1&var-device_urn=note:dev:864475041076562 and isn't expensive for a single device on a small (<90 days) timescale.

**Comment by matschaffer** [comment]
If you don't think our current map is a good fit for the "zoom out to see my device contributing to the world" use case, we could explore other options.

I often look at https://www.iqair.com/air-quality-map as a great example of what might be possible, but I'm sure building that took a lot of work and I don't think any of it is open in a way we could use it.

**Comment by matschaffer** [comment]
Totally rough, but maybe this helps depict the sort of thing I'm imagining the device owner could land on.

![Live_Animated_Air_Quality_Map__AQI__PM2_5_______AirVisual](https://user-images.githubusercontent.com/690/103115309-75830100-46a5-11eb-9bee-02fed22037f1.png)

**Comment by rayozzie** [comment]
Something like that would be amazing!  The reason I like it so much is not just the sexiness, but because (unlike radiation) it really gives you a sense that air is a fluid, and that looking at it is kind-of like the weather report.

**Comment by matschaffer** [comment]
@nokton @seanbonner @Frangible have we ever reached out to anyone at https://carto.com/ about this sort of thing? Seems like there must be some organization we can rope into giving us really nice mapping tools for free.

No idea if carto is good or not, but it seems to get a lot of hits when I google around.

**Comment by nokton** [comment]
Hi Mat,

Not aware we reached out to carto. WE did do some work w ESRI but don’t think we have free access to their tools. @frangible may know more.

Feel free to reach out to carto.com though!

**Comment by matschaffer** [comment]
Had a call with Carto, some notes:

- postgis is one of their main integrations
- https://deck.gl/ framework - something to explore, also has some carto ingegration
- CartoFrames - jupyter notebook integration
- They provide professional services to make full solutions: based on yearly subscription or one time separately priced
- They also have data sets https://carto.com/spatial-data-catalog/ - public data sets are included in some plan and also extra cost premium data sets
- They have a 150MB free plan but it lacks any sort of postgres connector
- The rep will get back to me about what potential cost might be on having Carto professional services build something, as well as if there's a way to experiment with the postgres connector without having to pay right away

**Comment by matschaffer** [comment]
Noticed https://kepler.gl/ in the UI as well which also looks interesting

**Comment by matschaffer** [comment]
<img width="291" alt="Safecast_Map" src="https://user-images.githubusercontent.com/690/114644659-e57bcc80-9d12-11eb-9a1c-8d4cac313349.png">

We should be thinking about how to display many sensors as well. Today on the map we don't do any sort of aggregation so the icons just overlap.

This will probably get very messy as we start to have thousands in the field.

**Comment by nokton** [comment]
As we talked, lets deploy the grafana air-only map by adding it to the data map. We can then reserve the current map as “radiation only”, and only show the radiation “circles” for any sensor that has a radiation sensor on board. AS first step lets get the grafana map going (and can the grafana map, when clicked on a sensor, go to the device story page or grafana device page?)

I can coordinate on getting the menu going, but will need the URL that we should use.

**Comment by matschaffer** [comment]
In talking to @jamoross today we're thinking we should drop this in favor of focusing on https://github.com/Safecast/safecastapi/issues/818

The analog to the bGeigie Log Viewer is probably not appropriate for the airnote data.

**Comment by nokton** [comment]
Lets focus on getting the world air data map going and iterate over time to make it better.
