### ISSUE TITLE
Ability to notify drive submitter with comments

### ISSUE THREAD

**Issue by nokton** [Safecast/safecastapi#75]
Currently we can only approve or delete.

Better would be to be able to "push back" with a comment. Including ability for submitter to delete own drive as long as it is not submitted for approval.

In case of deleting a drive, keep a log

Comment field for approver to make any observations

**Comment by matschaffer** [comment]
We do have a comment field, but it's just a cell and doesn't do any sort of notification, so rewording this issue to cover that.

**Comment by nokton** [comment]
I asked Ben to help with this and discussed in more detail how this could work - can you chat with Ben so we can update accordingly?
