### ISSUE TITLE
Airnote device story landing page

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#751]
We should make something like https://api.safecast.org/en-US/device_stories/34 but with a url of https://api.safecast.org/airnote/note:dev:865284040122792 (look up the device story via the urn in the path)
And just make it a new page that's mobile friendly.

Eventually we'll redirect the on-device QR codes to that page.
![Image_from_iOS](https://user-images.githubusercontent.com/690/103048708-d2fa4d80-45d2-11eb-8779-fc3074ef2bd2.jpg)

Let's plan to break out of the usual app layout for this one so we can be mobile friendly since that's how people will scan the code.

Some feature ideas:
- If we don't have the device urn in the DeviceStories yet, display some sort of help page to ensure the device is mounted reasonably (@nokton or @robouden can provide some content)
- Display the graphs from https://grafana.safecast.cc/d/7wsttvxGk/airnote-device-details (air-specific) instead of https://grafana.safecast.cc/d/DFSxrOLWk/safecast-device-details (radiation-specific)

**Comment by robouden** [comment]
But do not use the solar cast tracker sheet data. Users should be able to access the page without having to login, or maybe we should #forced" to make an account first? 

A bit too much trouble I think if they already registered at Notehub with their pin. Or can we make auto registered with the URL has the pin and username  info etc ?

**Comment by matschaffer** [comment]
> But do not use the solar cast tracker sheet data.

Nothing in API uses the tracker directly today. If ttserve returns tracker data (via `/devices`) API stores that, but I think that's unlikely for the airnotes. We'll just have the urn and some "last seen" info which is fine. We can allow users to populate the rest via some sort of form as a "phase 2" I think.

>  Users should be able to access the page without having to login, or maybe we should #forced" to make an account first?

I'd ignore the question of login for the first round.

At some point I think we'll want something that allows field modification if a logged in user reaches the page with valid (as confirmed by notehub api) PIN. But as @rayozzie recommended, let's not try to solve that problem today.

> they already registered at Notehub

I was under the impression no safecast airnote user (perhaps no airnote user at all) would directly interact with notehub, but let me know if I got something wrong there.

> Or can we make auto registered with the URL has the pin and username info etc?

@rayozzie said the main devices would ship with a sticker that was linked to the notehub project with a PIN, so I think we're good there.

**Comment by rayozzie** [comment]
To be clear in answering the above, 
- Airnote devices autoprovision on notehub just as any notecard-based device, with zero user interaction or involvement.  Of course, this means that the devices are anonymous.
- There is no difference between a “safecast airnote user” and an “Airnote user”.  From the device and user perspective, the device sends data to a notehub project and it is up to that project who to route it to.  In this case, the “Airnote” project (the default target that is used out of the box) is configured so that Safecast is one route, snd there may ultimately be others such as a “data warehouse” or alternative visualization or a specialized “broken device watcher”.

**Comment by matschaffer** [comment]
Thanks @rayozzie. I guess what I'm wondering is if we'd ever have the QR sticker ever redirect so something other than a safecast landing page. But pretty sure that'd have to be another notehub project to do so.

**Comment by rayozzie** [comment]
- I have not yet discussed whether or not we (Blues) are going to write the code to let users modify env vars, or if it is appropriate to delegate this to Safecast.  The main issue is that this involves read write creds to the entire fleet, and the blues dev team may want to keep it read-only to external services for the short term.

as I said, I think in the short term it is best that we concentrate on visualizations and I hope just after the new year we have a bit more clarity on some of these issues.

thanks for your patience!

**Comment by matschaffer** [comment]
Sounds good. Let's ignore the "[user] already registered at Notehub with their pin" flow @robouden mentioned for the time being then.

**Comment by rayozzie** [comment]
I edited the comment, so let me reiterate that it’s my goal to figure out how to get /devices in ttserve enhanced with as much knowledge as possible, knowing that there is no xlsx to rely upon.

**Comment by robouden** [comment]
Not Emre has done a great job on getting the comments and the mobile styling going, I would like to see an option to upload pictures.

BTW. For the comments maybe we should get a Captcha going to prevent spam?

**Comment by Nakushi64** [comment]
Already started working on the picture uploads. Also we use the Akismet framework to prevent spam via the rakismet gem.

**Comment by robouden** [comment]
Just wondering why @matschaffer closed the issue.

**Comment by matschaffer** [comment]
GitHub closes on merge if linked prs. Will be in prod soon now that we fixed the errors in master
