### ISSUE TITLE
Add a donate/store banner to bgeigie_imports#show

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#780]
To help drive donations, we'd like to add some banner material to https://api.safecast.org/

People who upload or browse into specific drives seem like likely candidates for helping out with the project further, so we'll try adding something there for starters.

Here's a rough idea. Probably something a little more styled, of course.

![Screen Shot 2021-03-02 at 9 23 20](https://user-images.githubusercontent.com/690/109577484-fbee1000-7b38-11eb-8a58-dfd302617012.png)

**Comment by robouden** [comment]
Yes, agreed.. This what I also think is needed.

**Comment by matschaffer** [comment]
Looks like donate should probably go to https://safecast.org/donate/ and store to https://shop.safecast.org/

**Comment by ZacharyCChang0828** [comment]
I am able to put together a basic version of the donate banner like the one above but I am not quite sure how we want to style it more. Using buttons for the links instead of simple text hyperlink maybe?

I think the current design looks nice in the way that it is flat and people can still see most of the important information when they click into an import page.

**Comment by matschaffer** [comment]
It probably makes sense to at least use a bootstrap notification style. What I did there was just raw in-line styles. 

For the links just a regular link_to is fine I’d say. Button might be overkill. 

Let’s get something into a Pr and we can put that in dev for feed back

**Comment by ZacharyCChang0828** [comment]
Just created a PR and linked this issue to it. I will look into making it a bootstrap notification style

**Comment by ZacharyCChang0828** [comment]
I'm not sure if using alert-warning is the right call but here's what I have for now

![image](https://user-images.githubusercontent.com/35931293/120471027-caeed700-c3d6-11eb-8d05-dd897274cfb7.png)

**Comment by matschaffer** [comment]
Yeah I think the extra yellow without the x is better

**Comment by ZacharyCChang0828** [comment]
> Yeah I think the extra yellow without the x is better

Is this referring to the previous version? Also the x is for collapsing, can remove that if we don't need that functionality.

**Comment by matschaffer** [comment]
I’d leave the “x” out I think. Just always show it.
