### ISSUE TITLE
Load in cs-CZ translation

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#782]
Apparently [Jan](https://twitter.com/jhelebrant/status/1367814863372877824?s=20) added all the cs-CZ translations to https://app.localeapp.com/projects/4489/translations?in_locale=27959

Seems like there should be some way to get this back in the app for more localizations beyond english and japanese.

**Comment by matschaffer** [comment]
Looks like it got removed back in https://github.com/Safecast/safecastapi/commit/799b01c5b22c9c74e3fa162e6b659d4e739953a6 - nothing saying why.

Not sure if we want to continue using it, but it'd be good to at least commit the translations from Jan to git so we can leverage his work.

**Comment by eitoball** [comment]
It is on api.safecast.org now.
