### ISSUE TITLE
Add "global map" link to device stories page

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#789]
https://api.safecast.org/en-US/device_stories/191 should have some link back to the global map. Perhaps near the "more sensor data" link.

Could probably link to https://grafana.safecast.cc/d/t_Z6DlbGz/safecast-all-airnotes?orgId=1 for airnote devices.

Non-airnote devices can link to https://grafana.safecast.cc/

**Comment by robouden** [comment]
There are other requests/suggestions for the device story pages. Like having the last reading on top and big in uS/h instead of CPM. The discussion can be viewed at [](https://www.youtube.com/watch?v=o6VuTAIiHMg)
