### ISSUE TITLE
Fix grafana map panel on 7.5.2

### ISSUE THREAD

**Issue by matschaffer** [Safecast/safecastapi#795]
I tried to upgrade grafana to 7.5.2 but it causes some error on the map panel.

<img width="856" alt="Screen Shot 2021-03-31 at 8 45 23" src="https://user-images.githubusercontent.com/690/113070587-e2a2b700-91fd-11eb-8b33-09a93036acbb.png">

We're using https://github.com/panodata/grafana-map-panel/releases/tag/0.15.0 which is the latest release. So we'll have to either fix the bug or wait for @amotl release a fix then upgrade to that, potentially.

**Comment by robouden** [comment]
Maybe wait for Andreas to fix it?

**Comment by amotl** [comment]
Hi Mat and Rob,

thank you for reporting this. I just created https://github.com/panodata/grafana-map-panel/issues/95 in order to investigate the problem further. I will be happy about any more feedback in order to be able to mitigate the issue efficiently.

With kind regards,
Andreas.

**Comment by matschaffer** [comment]
Unfortunately things work fine locally. Thinking I'll intentionally break the main site for a few minutes to try to see what the error is. Dev is docker, but prod is based on an old beanstalk image, so we aren't set up to perfectly replicate between the two atm.

![Screen Shot 2021-04-05 at 8 01 20](https://user-images.githubusercontent.com/690/113523808-24a87000-95e5-11eb-9a2f-0403e7011ac4.png)

**Comment by matschaffer** [comment]
And... this time it's fine. Guess we're good here. Sorry for the noise folks.
