### ISSUE TITLE
Undefined method dig' for #Elasticsearch::Model::Response::Response:0x...

### ISSUE THREAD

**Issue by eitoball** [Safecast/safecastapi#806]
https://github.com/Safecast/safecastapi/pull/786#pullrequestreview-638294301

---

I put this on dev but it's getting undefined method dig' for #Elasticsearch::Model::Response::Response:0x0000000007d4ee58`

https://5bc3d4f7330a4459881197a85659caf5.us-west-2.aws.found.io:9243/app/apm#/services/safecastapi-dev/errors/1baaae338359071560c867ba08f88b5c?rangeFrom=now-15m&rangeTo=now&refreshPaused=true&refreshInterval=0

**Comment by matschaffer** [comment]
Thanks for opening this properly!
