### ISSUE TITLE
Usv at al.

### ISSUE THREAD

**Issue by thinrope** [Safecast/safecastapi#82]
Occasionally I see things like uSv, Usv and so on. 99% of these places it should be μSv/h instead or actually DRE (Dose Rate Equivalent) like DRE: 0.34 μSv/h . Similarly, CPM should be "count rate: 34 CPM"
(think of "price: 5 USD" vs. "dollars: 5")

Also uSv/h may be acceptable in a DOS or 8-bit MCU, but modern Ruby-based, i18n-aware Web app for a global project?!?

One example is in the map view of bGeigie import... I am guessing this is where it is defined: https://github.com/Safecast/safecastapi/blob/master/app/views/bgeigie_imports/_map.html.erb#L31

Will track other occurrences here, don't close for some time.

**Comment by matschaffer** [comment]
Closing since git grep doesn't find any uSv or Usv and the linked label is already corrected.
