### ISSUE TITLE
numbers used for hover on maps, etc. should be styled with fixed-width font

### ISSUE THREAD

**Issue by thinrope** [Safecast/safecastapi#84]
Otherwise moving the mouse changes the rendered width too much and it is hard to see whether the value changes significantly or not due to the left<->right shifting of the decimal point.

li.WHATEVER {font-family: "Lucida Console", Monaco, monospace;} should do for bGeigie imports|Map view.

**Comment by seanbonner** [comment]
Assigning to @Frangible to decide on and or close.

**Comment by Frangible** [comment]
Recommend resolution by replacing the legacy API log viewer with bgeigie_viewer.js (from http://github.com/Safecast/Tilemap).   Likely need someone with Ruby experience to implement.

**Comment by thinrope** [comment]
Duplicate/subset of issue #197
