### ISSUE TITLE
export/dump of the whole database tune-up needed

### ISSUE THREAD

**Issue by thinrope** [Safecast/safecastapi#85]
I'll play around a bit with what might be a good way to export the data.

Does anyone know if we have any regular users of the data (grep the access logs for a script-like fetching system/measurements.tar.gz)??

For a start, it being a single file it should be measurements.gz only, but that may break other people's scripts.

I'll put everything on a separate branch: https://github.com/Safecast/safecastapi/tree/issue85

**Comment by seanbonner** [comment]
Old issue that has been worked on and changed quite a lot and might be resolved, if not resubmit as new issue please.
