### ISSUE TITLE
Flight Data

### ISSUE THREAD

**Issue by seanbonner** [Safecast/safecastapi#88]
We need a flag of some sort that we can specify when we are safecasting from a plane rather than from the ground. Right now our map/data is 2D which makes this confusing

ie - this would look like a super contaminated route, rather than a flight
https://api.safecast.org/en-US/bgeigie_imports/11188

This is going to be a big deal when we make it public so need to be assured it's presented correctly.

**Comment by matschaffer** [comment]
Fixed by #243
