### ISSUE TITLE
Sorting on "awaiting approval" page is wrong

### ISSUE THREAD

**Issue by seanbonner** [Safecast/safecastapi#92]
On:

https://api.safecast.org/en-US/bgeigie_imports

Many files that have been approved are still showing in awaiting approval, many files that have been submitted are still showing in processed, etc. Sorting is off. And once something has been fully approved it's still showing for days in the list awaiting approval.

**Comment by matschaffer** [comment]
@seanbonner the link you have there is the "all" page now. We have https://api.safecast.org/en-US/bgeigie_imports/not_approved now which seems to be an accurate list (though not sortable).

Will close this out since it's probably been fixed by other efforts around these links.
