### ISSUE TITLE
Couldn't post measurement

### ISSUE THREAD

**Issue by eyesjapan** [Safecast/safecastapi#96]
In the project FukushimaWheel, we would like to post measurement, which iOS app receive from bGeigieNano, to server. 
I request with the following url: **https://api.safecast.org/measurements.json?api_key=[api_key]**
with the following data content:
**{
  "captured_at" : "2013-02-19T05:41:00Z",
  "device_id" : "0210",
  "location" : "POINT(139.926985,37.485201)",
  "unit" : "cpm",
  "value" : "22.99"
}**
However get the following error message from server:
**{"errors":{"location":["can't be blank"],"value":["can't be blank"],"unit":["can't be blank"]}}**

Did I do something wrong?

**Comment by j0ry** [comment]
looks resolved - marking closed
