### ISSUE TITLE
Add button for approver to send an email to submitter of drive data (use email client to email - no need to keep log in application)

### ISSUE THREAD

**Issue by nokton** [Safecast/safecastapi#99]

**Comment by matschaffer** [comment]
Pretty similar to #75 and #130 - not sure which ones to close but at least mentioning them so maybe we can address them as a group.

**Comment by jsidd** [comment]
Ok so there is indeed a problem with this on production. The server is not letting us send an email using the sender/logged in user or approving/rejecting moderator in the from field. I am going to change the from email to mailer@safecast.org and similar to the notification email notify the user/moderator with the message sent.
